### ISSUE TITLE
Display status of recorder on webpage.

### ISSUE THREAD

**Issue by robotastic** [robotastic/trunk-recorder#1]
The goal would be a way to display system information about the number of calls currently being recorded and information about the trunking system. This information would be sent out as JSON over a localhost port to a node.js server. Node.js would handle updating a dashboard and serve up the page locally. It would make it really easy to check on what is happening with the recorder while it is on your network.

**Comment by amlethojalen** [comment]
I'm in the process of doing a dashboard at the moment, it uses nodejs and the status socket, i'm happy to add all the source into this project to keep it all together if you want.

**Comment by amlethojalen** [comment]
If you send me an email, i can send you a link to the test page i'm working on (its public but hidden at the moment)

**Comment by robotastic** [comment]
Awesome! I will send you an email. I am still getting everything documented around status socket. I have a sample server here: https://github.com/robotastic/trunk-recorder-status-server
it is ugly though.

**Comment by amlethojalen** [comment]
I've got some pretty basic doco on the json messages that i implemented, they are in the PR, i'll clean up my implementation a bit before i make it public. There was only one breaking change which changing the rates to be an array of rates instead of key value set.

**Comment by allonucleus** [comment]
Made a pull request that fixes it

**Comment by robotastic** [comment]
This is largely handled through the Status Server and MQTT.
