### ISSUE TITLE
Add startup option for config file path

### ISSUE THREAD

**Issue by kkotowick** [robotastic/trunk-recorder#101]
Would it be possible to add a command-line startup option to "./recorder" that can specify the path of the config file? I have a couple config files I switch between, and it would be great if a) I could have them in a different directory, and b) didn't have to rename them every time I switch to a different one. Perhaps something like:

`./recorder --config="../configs/trunked.json"`

**Comment by robotastic** [comment]
That is a great idea - I have been copying the config files back and forth,
which is a pain. I will get this in there... should be a pretty easy lift.

**Comment by robotastic** [comment]
Added to the latest update, in develop branch
