### ISSUE TITLE
Patch Tracking

### ISSUE THREAD

**Issue by kcwebby** [robotastic/trunk-recorder#108]
Enhance patch tracking in logs...   When its assigned / removed and which talkgroups are involved in the patch.

This would help prevent multiple recordings on different talkgroups when they are patched.
Could record as "TG XXXX, TGXXX, TGXXXX as Patch XXX" and

**Comment by leee** [comment]
@robotastic: you could close this issue as an older dupe and roll it into #368.

**Comment by robotastic** [comment]
Agreed - moving to #368
