### ISSUE TITLE
Auto Gain Control

### ISSUE THREAD

**Issue by kcwebby** [robotastic/trunk-recorder#109]
Automatically Adjust Gain (normalize) volume on recordings to be within a normal range (by transmission)

**Comment by nkwood** [comment]
The easiest way to do this probably is to normalize the audio as part of the ffmpeg processing or another utility (e.g. https://github.com/slhck/ffmpeg-normalize or http://ffmpeg.org/ffmpeg-all.html#dynaudnorm) rather than on the fly in the recorder.

**Comment by mndmr** [comment]
How would this be accomplished before the file is uploaded to openmhz?
