### ISSUE TITLE
Volk error allocating memory (posix_memalign: 22)

### ISSUE THREAD

**Issue by chudgoo** [robotastic/trunk-recorder#114]
Hello all, 
I'm trying to get Trunk Recorder running on an ODROID C2 single board computer running DietPi and am seeing the following error:

Using Volk machine: generic_orc
VOLK: Error allocating memory (posix_memalign: 22)
Segmentation fault

This system has 2GB of RAM and has 1.7GB available memory...
Has anyone seen this before?

**Comment by robotastic** [comment]
This might have something to do with the version of GnuRadio you are using. I think it got patched in newer versions:
https://bugzilla.redhat.com/show_bug.cgi?id=1185710
