### ISSUE TITLE
master will not decode smartnet controll channel

### ISSUE THREAD

**Issue by dreinhold** [robotastic/trunk-recorder#126]
Just tried master on a new machine, could not get it to decode anything on my smart-net control channel. Switched the the development branch and its decoding fine, same HW, same config.json settings.

**Comment by robotastic** [comment]
Weird - I think I have things working with on my local SmartNet system....
I will check on that. I think I may have changed something on the input
filter to make it tighter. Are you sure you have error set correctly? The
version in Master may be a little pickier.

**Comment by dreinhold** [comment]
Yeah I must have, i went back an re tested again and it seems fine..
