### ISSUE TITLE
Excessively fast playback for conventional signals

### ISSUE THREAD

**Issue by lkjww** [robotastic/trunk-recorder#128]
Hi, I have got everything setup and configured, but on two separate machines (x86 and pi) while using a rtl-sdr to decode analog signals, the audio is excessively "fast" Oddly it seems to remain the same pitch, but it is playing a a much to fast rate... Talking sounds very rapid and impossible to understand. Not sure what could be the cause. Have tried several different bandwidth speeds and everything seems to be of no value.

**Comment by chudgoo** [comment]
I'm seeing the exact same issue on my install on a Pi 3.
I don't see anything in the logs to indicate why.  I am seeing a lot of "OOOOOOOOO" though... What does that indicate?

**Comment by robotastic** [comment]
Weird - This is off of the master branch? Could you post your config file? I am recording analog and it is working fine. 

For the 'OOOO's that just means the Pi 3 is getting overloaded. It can't handle too much at once, way just a single recorder.

**Comment by dreinhold** [comment]
Well the overruns (OOOOOO's) I guess could cause the wav to sound sped up. If you are only capturing some of the data in the wav. When you play that back, it would sound fast
