### ISSUE TITLE
CMake: Change project name from gr-osmosdr to smartnet-recorder

### ISSUE THREAD

**Issue by jynik** [robotastic/trunk-recorder#13]
The project CMakeLists.txt contains:

```
project(gr-osmosdr CXX C)
```

This admittedly threw me for a bit of a loop when I got an error message that gr-osmosdr couldn't be build due some missing deps.  Changing that to smartnet-recorder is probably a good idea. :)

**Comment by robotastic** [comment]
Good call! I will make the update. I clearly borrowed the code
