### ISSUE TITLE
TG File for Conventional systems

### ISSUE THREAD

**Issue by robotastic** [robotastic/trunk-recorder#152]
Change how talkgroups work for conventional systems. Instead of having the talkgroups defined by the order they are listed in the config.json, use the frequency of channel instead.

**Comment by dreinhold** [comment]
Because the talkgroup file ignores the 2nd column (HEX) for trunk groups we could put the frequency in there, and then you could use the same talkgroup file for a trunked and conv system.

**Comment by amlethojalen** [comment]
I've sort of done something similar to this, I've added talkgroup tags to the conventional channels.
see pull request #164 commit edafb90d
