### ISSUE TITLE
ENHANCEMENT: Ability to mail recordings or run commands per tg

### ISSUE THREAD

**Issue by netsound** [robotastic/trunk-recorder#154]
Looking for the ability to define certain talkgroups that when files are recorded they are emailed off depending on what talkgroup is recorded... IE paging talkgroups.   Or the ability to run certain commands based on certain talkgroups.

**Comment by rosecitytransit** [comment]
The uploadScript option will run a command after each file has completed recording with the filename as a parameter, and the talkgroup is the first part of the filename.  So set it in config.json and create a script that parses the filename and then does what you want.

**Comment by vabiro** [comment]
@netsound here is how I am getting the TGID out of the filename in my bash script. Once you have that you can do an ```if``` that will perform the action you need.
```
#! /bin/bash
echo "Encoding: $1" 
filename="$1"
basename="${filename%.*}"

fileid=$(basename $filename)
outdir="/root/recorder/audio/txcoded/"
outname="$fileid.wav"
tgid="${fileid%-*}"
```
I hope this gets you started.
