### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by Nokoa** [robotastic/trunk-recorder#169]
I might just be stupid but when I run ./recorder I get this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

On raspberry pi 3 B running debian

**Comment by Nokoa** [comment]
I set the locale through the pi's gui configuration it fixed it.

**Comment by Jims-do** [comment]
I am having the same issue too, have tried to change locale settings to different things but it still is not working, any suggestions
