### ISSUE TITLE
Keeps saying control channel decode rate, but not working

### ISSUE THREAD

**Issue by Nokoa** [robotastic/trunk-recorder#170]
Now I am quite confused because I got it to work once, and then I restarted the application and it started saying the decode rate and that I only have one control channel. I am pretty sure I set everything right. I do not have access to the device it is currently hosted on at this right moment so I cannot provide you with any data yet.

**Comment by Nokoa** [comment]
Sometimes it works, like it just did but the recordings all sound encrypted, while they are not.

**Comment by UnderwaterHockey** [comment]
Typically this happens to mine when the SDR's overheat.
