### ISSUE TITLE
adding another system

### ISSUE THREAD

**Issue by mnfire2** [robotastic/trunk-recorder#171]
I have this site on now [http://www.radioreference.com/apps/db/?siteId=5820](url)  i am running 5 srd

im wondering is it possible to monitor this site too [http://www.radioreference.com/apps/db/?siteId=5819](url) by adding a 6th sdr

thanks,
matt

**Comment by mndmr** [comment]
Yes, you can have as many systems as you want its all dependent on the amount of recorders (43 needed for both sites) that your PC will be able to handle and the RF spectrum that you need to cover (for both sites 9.875 MHz + band edge roll off of the SDR). Recently @rosecitytransit  submitted a request [different sites of same system not being kept separate](https://github.com/robotastic/trunk-recorder/issues/180), this would be a great improvement.

    "systems": [{
        "control_channels": [852362500.0, 852162500.0, 852287500.0, 853837500.0],
        "type": "p25",
        "talkgroupsFile": "armer.csv",
	"shortName": "hcearmer",
        "recordUnknown": false
	}, {
        "control_channels": [852612500.0, 852262500.0, 853637500.0, 853887500.0],
        "type": "P25",
	"shortName": "hcwarmer",
        "talkgroupsFile": "armer.csv"
        "recordUnknown": false
    }]
