### ISSUE TITLE
Issue setting up P25

### ISSUE THREAD

**Issue by willwjr** [robotastic/trunk-recorder#176]
Hello, 

I have setup the system on a RPi3 with 3 SDRs.  I have not been able to get past the following message when I start the system - 

[error] [delco]	There is only one control channel defined

Here is my config.json - 

    "sources": [{
        "center": 770500000,
        "rate": 2048000,
        "error": -30500,
        "squelch": -56,
        "gain": 20,
        "debugRecorders": 0,
        "digitalRecorders": 4,
        "modulation": "qpsk",
        "driver": "osmosdr",
        "device": "rtl=00000001"
    }, {
        "center": 856000000,
        "rate": 2048000,
        "error": -30500,
        "squelch": -56,
        "gain": 20,
        "digitalRecorders": 4,
        "modulation": "qpsk",
        "driver": "osmosdr",
        "device": "rtl=00000002"
    },{
        "center": 772500000,
        "rate": 2048000,
        "error": 0,
        "squelch": -56,
        "gain": 30,
        "debugRecorders": 0,
        "digitalRecorders": 4,
        "modulation": "qpsk",
        "driver": "osmosdr",
        "device": "rtl=4"
    }],
    "systems": [{
        "control_channels": [773081250],
        "type": "p25",
        "talkgroupsFile": "DelCo.csv",
				"shortName": "delco"
    }],
    "captureDir": "/home/pi/trunk-recorder/recordings",
    "logFile": true
}

Yes I have only one Control channel defined, but that is the channel they are using.  When I connect to the channel on the RTL with SN of 4, i can clearly hear the P25 traffic with the settings I have.  I am not sure what is failing, since the only information I am receiving is "[error]".  I have tried both "qpsk" and "fsk4" with no change.  The application loads all three SDRs with no issue.  Is this error a result of a failure during the decode of the P25 signal?  Anything else I can try?  I am attempting to listen to the Ohio MARCS system, which is Project 25, Phase 1 according to RR.

Thank you for your assistance all!

**Comment by FarvaTechnology** [comment]
Change your device ID to 0 1 2... Or 1 2 3.

I tried forever using card serial numbers... Wouldn't work.   As soon as I entered card index number... Worked great
