### ISSUE TITLE
RPI recording capabilities

### ISSUE THREAD

**Issue by kg6uyz** [robotastic/trunk-recorder#186]
What is the recording capabilities of running trunk-recorder on a RPI? How many trunk systems and channels can it handle?

**Comment by gallaway** [comment]
This is with 3 rtl usb dongles + raspberry pi 3. Looks like i have to use a laptop after all.
<img width="608" alt="screen shot 2018-07-05 at 9 06 12 pm" src="https://user-images.githubusercontent.com/35348333/42354827-733c1fa2-8097-11e8-96ed-24aba103d408.png">

This is during a not so busy time on the radio

**Comment by gallaway** [comment]
@kg6uyz i was running the standard configuration. But even with less recorder "maybe" one each I just dont think the RPi has the means for the task. 2 radio's with 2 recorders.... maybe but I would be worried about recordings being incomplete.

**Comment by Dygear** [comment]
Have you tried running `volk_profile` on your pi and then trying it? You _might_ see some performance improvement as it will know the correct Vectored Kernal to use for your hardware.
