### ISSUE TITLE
LimeSDR support through SoapySDR

### ISSUE THREAD

**Issue by Treehouseman** [robotastic/trunk-recorder#188]
The antenna is unable to be set through the antenna value in the osmosdr block. I see there's provisions for setting an antenna on usrp (though using the usrp block) but not one for osmosdr. 
Manually adding the line 
`cast_to_osmo_sptr(source_block)->set_antenna("LNAW");`
to source.cc in the antenna function sets it properly, the config takes a string, with the lime sdr being values of "NONE" "LNAL" "LNAH" "LNAW" "LB1" "LB2".

Beyond that it seems the lime sdr works perfectly as intended with soapysdr, just add in the other gains (bbgain, ifgain) like with the hackrf and change the device string to "soapy=0,driver=lime".

**Comment by MaxwellDPS** [comment]
at line 14 in sources.cc does this have to be replaced?

> cast_to_osmo_sptr(source_block)->set_antenna(antenna, 0);

or can cast_to_osmo_sptr(source_block)->set_antenna("LNAW"); just be added to line 15
