### ISSUE TITLE
Real-time audio enhancement

### ISSUE THREAD

**Issue by madengr** [robotastic/trunk-recorder#19]
trunk-recorder is awesome.  I have been using it on our trunked system in Johnson County, KS.  Could you add audio so one can listen in real-time?  Perhaps combine all the demodulator outputs via non-blocking squelches, a multi-input adder, and audio sink.

**Comment by robotastic** [comment]
I might be able to. I could just do some basic coordination between the recorders so only one is outputting audio at a time. It might be easier to setup a local app or website that monitors the recording dir and lets you listen to the audio.
