### ISSUE TITLE
Need help upgrading, not getting P25 radio IDs

### ISSUE THREAD

**Issue by rosecitytransit** [robotastic/trunk-recorder#200]
I am trying to update from the ancient gr-latency branch from which @robotastic added unit-unit call support and am having some issues.  It appears that in this commit https://github.com/robotastic/trunk-recorder/commit/3f64de33e23408f95912826ff7d5b827919ac9f5 the code was changed from getting radio IDs from the voice packet metadata to getting them from the control channel.  However, the system I record only occasionally puts radio IDs on the control channel.

I use radio IDs to handle unit-unit calls which don't show up correctly on the control channel so it is important to have them.  I am wondering if someone can change my https://github.com/rosecitytransit/trunk-recorder/tree/trimetscanner branch so it gets radio IDs from voice packets.

In addition, I am trying to start recording from a second site, and at first things work great but after half a day or so, I start getting an increasing amount of 44 byte files.  I don't think it's a signal issue as the decoding issue remains great.  I am hoping the upgrade will address this.

**Comment by kg6uyz** [comment]
I was having the 44 byte file problem.  Make sure you have a tuned antenna
for the frequency spectrum your recording..  I also bought some big heat
sinks to dissipate heat on my sdr's that ran super hot.  Seems to have made
things better....

**Comment by rosecitytransit** [comment]
I'm not sure that's the issue as I'm using the same bandwidth settings when I add the second site (1.8 MHz for each SDR) and I thought all of the work was done in software, meaning the same data is getting pulled in.

Also, if there's not an antenna covering a frequency, no file will show up since it won't even try to record.

**Comment by rosecitytransit** [comment]
I still haven't solved this problem, and a listener is willing to pay whoever to help solve it.  I'd really like to figure out why audio starts failing to record with the second site, but if I could at least get the program updated that would be a success.

**Comment by rosecitytransit** [comment]
Still interested in compensating someone to help me with this

**Comment by rosecitytransit** [comment]
Well, I don't know if they're coming from the control channel or the voice frames, but I appear to be getting the radio IDs.

I'm now trying to detect call terminations on the voice channels. So far, I have 871f6a3 but I get segmentation faults every time a call ends.
