### ISSUE TITLE
rates

### ISSUE THREAD

**Issue by dreinhold** [robotastic/trunk-recorder#212]
Does anything in the code rely on specific input rate? Using a bladerf, i can use 10megs, but not 9 or 12?

**Comment by robotastic** [comment]
That is a good question - it may have to do with the filters that are part of the decode. They setup the ratios based on the sample rate… Maybe setup some print statements and see if you are getting weird values.

**Comment by dreinhold** [comment]
Thanks Luke. I'll dig around. Going to close this out. If I find anything ill post it.
