### ISSUE TITLE
Trying to debug missing audio

### ISSUE THREAD

**Issue by dreinhold** [robotastic/trunk-recorder#215]
Working on debugging why i'm missing so much audio. It's a p25 P1 system.
I get a great 40mesg/sec from the control channel. But i'm missing (creating the wav with header only) a large amount of audio. 
It feels like the missing audio come in groups, I get a good audio on the first transmission then the next 2 are empty then it's good. I don't think the system is being overwhelmed.

[2019-01-10 16:13:09.996453] (info)   	 P25 Recorder Initial Rate: 500000 Resampled Rate: 31250 Initial Decimation: 20 Decimation: 16 System Rate: 30000 ARB Rate: 0.96
[2019-01-10 16:13:09.996482] (info)   P25 Recorder Taps - initial: 1515 channel: 1515 ARB: 757 Total: 3787

These are the p25 recorders build built.

Ideas to try??

**Comment by robotastic** [comment]
I would check to see if it is particular frequencies that aren’t working well. I had a system where there was a strong signal nearby and it was canceling out most transmissions on that freq… that HackRF doesn’t seem to have the best filtering and can be overwhelmed by nearby strong transmitters.

**Comment by dreinhold** [comment]
It's pretty even across all the frequencies. It's weird the control channel is sold 40's all day a couple 39's followed by the 41 to make up for it.

**Comment by dreinhold** [comment]
I started to think logically about this.
So if it was interference I would expect it to decode some audio and be garbled , but I was getting nothing in those transmissions. Getting nothing started to point that the decoder was not getting anything in. So more gain and it helped. The control channel being at 40 was giving my a false sense that the gain was good.
