### ISSUE TITLE
Documentation Correction: DigitalLevels attrib

### ISSUE THREAD

**Issue by dkettmann** [robotastic/trunk-recorder#219]
I believe the documentation might be incorrect when it states the default value is 8 for the DigitalLevels setting.  

I needed to boost my volume, so set it to 11 and it was *very* loud.  I worked my way back on it and ended up with a value of a 3 giving a nice sized boost.  Then I looked inside main.cc here and noticed that perhaps line 308 shows a default value of 1?

**Comment by robotastic** [comment]
Good catch - just made the change... I am a little back logged on fixing issues.

**Comment by robotastic** [comment]
Thanks!!
