### ISSUE TITLE
delayCreateOutput for Conventional

### ISSUE THREAD

**Issue by frameshift18** [robotastic/trunk-recorder#220]
I saw there is a delayCreateOutput option for conventional P25 but I don't think there is something similar for analog conventional?

When I have analog conventional recorders running the file seems to be created right away so the timestamp for the analog recording is the time the recorder started, not when the actual frequency activity started.

I would think delayCreateOutput for analog conventional would be the fix for this?

**Comment by mdozier9** [comment]
Would a simple touch post-record script work?  Or is the timestamp derived from the filename?  I have the same issue with conventional and conventional P25 systems.  In my lower-traffic systems, I've seen the time stamp be off by as much as 45 minutes.  It would be nice to have them show up with a more accurate timestamp.
