### ISSUE TITLE
Support static linking

### ISSUE THREAD

**Issue by Gibby** [robotastic/trunk-recorder#226]
I am working on a docker container that includes trunk-recorder and trunk-player (https://github.com/Gibby/sdr-trunk) and trying to keep the size down by building with static libraries but looks like the source for libgnuradio-op25_repeater is not in the repo.

I run cmake with this command:
`cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static" ./`

On make I get this error:

> /usr/bin/ld: attempted static link of dynamic object `lib/op25_repeater/lib/libgnuradio-op25_repeater.so'
collect2: error: ld returned 1 exit status
CMakeFiles/recorder.dir/build.make:802: recipe for target 'recorder' failed
make[2]: *** [recorder] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/recorder.dir/all' failed
make[1]: *** [CMakeFiles/recorder.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I saw in another issue that this is a customized op25 so I can't really grab it from another source. 

Any help would be great.

**Comment by robotastic** [comment]
Tracking under #365 - It is possible. The changes on the Static branch allow for this. Unfortunately, the gnuradio libraries you get from apt-get only give shared libraries: https://github.com/robotastic/trunk-recorder/issues/365#issuecomment-644490174
