### ISSUE TITLE
Low audio on conventional p25

### ISSUE THREAD

**Issue by imagesafari** [robotastic/trunk-recorder#230]
I've got a few conventional p25 systems where the audio is very low compared to others. I'm recording multiple "systems" of these in a single instance of trunk recorder.

Any ideas or tips on how to adjust or try to "normalize" the audio on the systems where it is low?

Thanks

**Comment by vabiro** [comment]
Have you tried adding "digitalLevels": 5, to the config.json file for the SDR(s)?
You could also run a bash script when a recording is made by adding "uploadScript":"scriptname.sh" to the system, and then something like:

`
     #! /bin/bash
     echo "Encoding: $1" 
     filename="$1"
     basename="${filename%.*}"
     fileid=$(basename $filename)
     outdir="/root/recorder/audio/txcoded/"
     outname="$fileid.wav"
     outencoded="$outdir$fileid"
     eval "nice -n 19 /usr/bin/ffmpeg -i $filename  -ac 1  $outencoded > /dev/null 
`
