### ISSUE TITLE
Feature: Radio ID Tags

### ISSUE THREAD

**Issue by s3m1s0n1c** [robotastic/trunk-recorder#237]
Would be cool to add a Radio ID Tags so U can see what radio ID belongs to what unit/car etc

Eg 1234 -> Car 234

This could just populate from CSV like talkgroups.

**Comment by ohaydel** [comment]
I second this feature 🥇

**Comment by dbuttry** [comment]
I would love to see this feature too!

**Comment by JoeGilkey** [comment]
I just put in a Pull Request that adds this to the call status output. There is a CSV file that gets loaded with the unit ID, tag and description, similar to talkgroups.
