### ISSUE TITLE
Unable to setup a system to record, exiting

### ISSUE THREAD

**Issue by chrkyl** [robotastic/trunk-recorder#239]
Brand new to trunk recorder and when i run it, i get a message that says "Unable to setup a System to record, exiting...."  I am sure it is something wrong in my setup I just cant figure out what

**Comment by vabiro** [comment]
@chrkyl You're going to have to post your config.json file, and tell us something about how your SDRs are configured (model and have you changed the serial number per https://github.com/robotastic/trunk-recorder/wiki/Configuring-a-System#multiple-sources)
That should give us a starting point to begin helping you.
