### ISSUE TITLE
recorder stops recording

### ISSUE THREAD

**Issue by imagesafari** [robotastic/trunk-recorder#248]
I've got a weird issue whereI have a recorder instance recording several conventional P25 channels as well as a couple conventional analog channels.

If left running, over time, it will stop recording some of those channels. After a restart, recording resumes.

Any ideas?

**Comment by kg6uyz** [comment]
I have a similar issue, on mine the p25 trunking recorder stops recording
after a long period of time not restarting tr.  My conventional recorders
dont get affected and continue to work.  I might have had one or two
occasions where my conventional recorders might have stopped recording.

**Comment by robotastic** [comment]
I haven't seen this issue before. Could it be the system hitting some limit around open files or something like that? I haven't run into this issue myself, but I am not recording Conventional. One option could be to setup a script to automatically reboot every night.
