### ISSUE TITLE
handle_message(){  not executing

### ISSUE THREAD

**Issue by brendanvg** [robotastic/trunk-recorder#25]
(In trunk-recorder) Because our current error comes from main.cc conditional statement: -> if (msgs_decoded_per_second < 10 ) with a friend I did some looking into the main.cc code today and found (by adding BOOST_LOG_TRIVIAL(error) << "put debug string here" error messages) that:

messages are never getting handled...
in main.cc the computer is never executing the code inside the function:
  void handle_message(std::vector<TrunkMessage> messages){  

i wonder why......

**Comment by robotastic** [comment]
Closing since there has been no update and the code has been updated to fix a lot of problems.
