### ISSUE TITLE
Not Receiving Anything

### ISSUE THREAD

**Issue by dh47** [robotastic/trunk-recorder#257]
I don't seem to be picking anything up.  There doesn't seem to be any errors so I'm not sure.
{
    "sources": [{
        "center": 1414000000,
        "rate": 2048000,
        "error": 0,
		"squelch": -50,
        "gain": 49,
        "debugRecorders": 0,
        "digitalRecorders": 4,
		"modulation": "qpsk",
        "driver": "osmosdr",
		"device": "rtl=0"
    }],
    "systems": [
        {
            "type": "conventional",
            "channels": [1414000000],
            "shortName": "EAS",
            "callLog": true,
            "audioArchive": true
}
],
  "captureDir": "/home/pi/radio/"
}

**Comment by frameshift18** [comment]
"center": 1414000000, is 1.414Ghz, do you have an extra 0? are you recording 2m analog amateur radio?

**Comment by dh47** [comment]
Ops, it's meant to be 141.400 MHz.

**Comment by frameshift18** [comment]
If you want to record analog conventional you need to use "analogRecorders" instead of "digitalRecorders" and don't put the modulation line. Since you only have 1 freq in the channels array you just need 1 Recorder.

**Comment by dh47** [comment]
What 141.400 MHz be for the config? 1414000?

**Comment by frameshift18** [comment]
what you had minus a 0, so 141400000, its in hertz

**Comment by frameshift18** [comment]
Also fair warning the analog recording on this is a little finicky. Your'e mostly likely gonna have to mess with your squelch setting or you'll get a bunch of random static recordings. Also the analog recorder works a little different than the digital so its going to act like its constantly recording but when the squelch breaks and there is traffic it will just save the audio after the squelch broke. Also the timestamps on the analog recordings seem to be offset by one recording.

**Comment by dh47** [comment]
Roger that.

**Comment by dh47** [comment]
What squelch setting do you recommend?

**Comment by frameshift18** [comment]
It all depends on your gain and strength of the signal you're wanting to receive.  Roughly between -30 and -60 but it varies. You'll just have to mess with it.

**Comment by dh47** [comment]
Ok now I have added another dongle and freq, the second channel is working but not the first is picking up nothing but static.  The squelch for both is set, am I missing something?

**Comment by dh47** [comment]
{
    "sources": [{
        "center": 141400000,
        "rate": 2048000,
        "error": 0,
		"squelch": -50,
        "gain": 49,
        "debugRecorders": 0,
        "analogRecorders": 4,
        "driver": "osmosdr",
		"device": "rtl=0"
    },{
        "center": 486500000,
        "rate": 2048000,
        "error": 0,
		"squelch": -50,
        "gain": 49,
        "analogRecorders": 4,
        "driver": "osmosdr",
        "device": "rtl=1"
    }],
    "systems": [
        {
            "type": "conventional",
            "channels": [141400000, 486500000],
            "shortName": "FTC",
            "callLog": true,
            "audioArchive": true
}
],
  "captureDir": "/home/pi/radio/"
}
