### ISSUE TITLE
audioArchive can't be false?

### ISSUE THREAD

**Issue by rpdale** [robotastic/trunk-recorder#260]
"systems": [{
        "control_channels": [853475000],
        "type": "p25",
        "talkgroupsFile": "ChanList.csv",
	"audioArchive":	false,
	"shortName": "mpscs",

My SD card is losing a few percent a day because it is keeping the old files. How do I set it up to not save them after it uploads to OpenMHZ?

**Comment by imagesafari** [comment]
Add a step to encode-upload to rm the file.
