### ISSUE TITLE
OpenMHZ Issues

### ISSUE THREAD

**Issue by rpdale** [robotastic/trunk-recorder#261]
1) The talkgroup page says priority > 100 is not recorded, but that seems to have no impact. Does the priority setting there do anything?

2) Speaking of talkgroup files - any way to use the same .csv file for both trunk-recorder and OpenMHZ? They seem to require a different format.

3) My 24-hour call history is always empty. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/11564694/63366930-c6b01180-c348-11e9-81f9-9dc34fa6a098.png)

**Comment by robotastic** [comment]
Setting priority on the Trunk Recorder side should stop talkgroups from being recorded. 

Yea - I have been thinking about trying to unify the file format, and make it easier it import from Radio Reference. 

Let me go try and debug the 24 hour call thing
