### ISSUE TITLE
Failure to exit cleanly after config parsing error

### ISSUE THREAD

**Issue by dlaw** [robotastic/trunk-recorder#275]
```
$ ./recorder 
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

[2019-10-27 19:01:00.550268] (info)   Using Config file: ./config.json

[2019-10-27 19:01:00.550528] (error)   Failed parsing Config: ./config.json(14): expected key string
[2019-10-27 19:01:00.550542] (error)   Unable to setup a System to record, exiting...
```

Expected behavior: `recorder` exits

Actual behavior: hangs forever (well, for at least 30 seconds); does not respond to Ctrl-C, Ctrl-D, or any other keyboard input. However, `pkill recorder` causes recorder to exit immediately.

My OS is Ubuntu 18.04.3 and the recorder version is 668fe62224ef7fb772d4263ed6f8c773683c0626. Please let me know if other information would be helpful.

**Comment by robotastic** [comment]
Just tested and can confirm this is a problem. Let me see what I can do to fix it. Had the same problem on OSX.
