### ISSUE TITLE
Signal level in info / debug output?

### ISSUE THREAD

**Issue by imagesafari** [robotastic/trunk-recorder#280]
Is there any way to include the signal level (relative to squelch_db) in the debugging output? It would make adjusting squelch levels much easier for marginal systems.

BOOST_LOG_TRIVIAL(info) << "TG: " << call->get_talkgroup_display() << " Freq: " << call->get_freq() << " Recorder: " <<  call->get_current_length() << " Idle: " << call->get_recorder()->is_idle() << " Count: " << call->get_idle_count();

**Comment by dandrzejewski** [comment]
Bit error rate would also be helpful.

**Comment by robotastic** [comment]
Unfortunately I have found a good/easy way to calculate signal level in GnuRadio. Happy to add this in if someone has one.
