### ISSUE TITLE
P25 on Analog channels

### ISSUE THREAD

**Issue by JoeGilkey** [robotastic/trunk-recorder#289]
A few years ago Motorola introduced something called TPS (Tactical Public Safety), which is a P25 header (Unit ID, etc) over an analog channel. This is the signaling that FDNY uses. I’m wondering how hard it would be to implement this on the Analog decoder channel. I’m thinking that the analog channel would need to pass the audio into the P25 frame slicer to start the decoder chain. Has anyone tried this before, or does anyone have any ideas?

Thanks,
Joe

**Comment by robotastic** [comment]
If anyone has some GnuRadio code that does this, I would be happy to try and integrate it.

**Comment by JoeGilkey** [comment]
@robotastic I figured out how to do this. I just need to connect the FM demodulator output to the FSK4 slicer and op25_frame_assembler, then parse the messages. I’ll clean up the code and add a pull request after #299 is in since it relies on that code.

**Comment by JoeGilkey** [comment]
FWIW, this is the signaling system that FDNY uses.
