### ISSUE TITLE
Add detail to "Not recording because of priority" log entry

### ISSUE THREAD

**Issue by mbt25** [robotastic/trunk-recorder#309]
I am recommending / asking if more detail could be provided for the "Not recording because of priority" log entry.

It would be very handy to know:
a.   the talkgroup not being recorded
b.   the reason (blacklisted, no recorder available)

So basically, include TGID and Priority # in the log entry

**Comment by robotastic** [comment]
@ginomiglio 's great PR should have fixed this - closing
