### ISSUE TITLE
Ideas for enhanced logging output

### ISSUE THREAD

**Issue by gofaster** [robotastic/trunk-recorder#310]
Per robotastic, opening up an issue to discuss ideas for changing stdout/log output from trunk-recorder.
While the current output is informative and visually appealing, it requires custom parsing/filtering routines in external processing/ingest apps.  These apps may break or require updating when t-r's log messages are changed.
It would be nice to have a standard and structured log output.
Perhaps something that follows the BSD syslog message header format (RFC 5424) with the message field structured in JSON like what rsyslog does?

t-r should emit log messages for all metrics, objects  and state changes that it is aware of.   External apps can ingest and process this for reporting or archiving.

Thoughts?

**Comment by robotastic** [comment]
I think we got a lot of this cleaned up
