### ISSUE TITLE
Issue with recording P25 Phase 2 traffic

### ISSUE THREAD

**Issue by CqDx914** [robotastic/trunk-recorder#311]
Hello, 

I have been using a Raspberry Pi 3 B+ with trunk-recorder installed and it’s doing a great job on decoding and recording P25 Phase 1 traffic, but when the network recently started carrying Phase 2 traffic, all it records were garble and unintelligible traffic. I see the logs reflect it recognizes TDMA traffic but it just would not record Phase 2 intelligibly.

Anyone has experienced this as well?

My raspberry pi is currently running on the following
Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018

Here is a sample of the trunk-recorder log that I captured:
[2020-02-07 21:57:46.454713] (info)   [METRO25]	TG: 9032	Freq: 8.530375e+08	TG not in Talkgroup File 
[2020-02-07 21:57:46.455067] (info)   	 P25 Recorder - Adjust Channel Resampled Rate: 30117.6 System Rate: 30000 ARB Rate: 0.996094
[2020-02-07 21:57:46.455979] (info)   	- Starting P25 Recorder Num [0]	TG: 9032	Freq: 8.530375e+08 	TDMA: true	Slot: 0
[2020-02-07 21:57:46.457004] (info)   [METRO25]	TG: 9032	Freq: 8.530375e+08	Starting Recorder on Src: 
[2020-02-07 21:57:52.001970] (info)   [METRO25]	TG: 9032	Freq: 8.530375e+08	Ending Recorded Call - Last Update: 4s	Call Elapsed: 6
[2020-02-07 21:57:52.015310] (info)   	- Stopping P25 Recorder Num [0]	TG: 9032	Freq: 8.530375e+08 	TDMA: true	Slot: 0

**Comment by robotastic** [comment]
It is definitely possible that the math gets mixed up on ARM chips. The only real difference between OP25 and Trunk Recorder for Phase 2, are these files: https://github.com/robotastic/trunk-recorder/tree/master/lib/lfsr
I will try to look through and see if I spot any obvious things where it is assuming

**Comment by GTR8000** [comment]
I also think that Phase II decoding is hosed up on the ARM platform.

We tried running on a Pi 3 B+ and could not get any intelligible audio from a TDMA system. Switched over to an ACEPC AK2 using the exact same RTL dongle and config.json, and decoding was excellent.

**Comment by CqDx914** [comment]
GTR8000 what distro did you use on the ACEPC AK2 may I ask? 
I had some luck setting up Ubuntu 18.04 using parallel desktop on my mac and got trunk-recorder working, but currently having problem with it using airspy dongle, so more experimentation on my side is needed..

**Comment by GTR8000** [comment]
Ubuntu 18.04.3 LTS, Trunk Recorder v3.1.2, with fdk-aac and sox also installed to support the OpenMHz change from ffmpeg encoding.

**Comment by edinburger** [comment]
Just started a new setup with RasPi4 (4GB) and am experiencing the same issues with TDMA recordings.  Garbled audio sounds like it is encrypted.  No issues with Phase-I TGs though.

**Comment by CqDx914** [comment]
I can confirm that when I use my Macbook Pro (much more horse power than Rp3 B+ obviously), I have no issue decoding Phase 2 traffic.

**Comment by mikewren** [comment]
Not sure if it's related, but I experienced the garbled audio issues on a P25 phase II system on talkgroups encoded as TDMA using a TR version from March.  Recompiled on 6/13 and it's not working perfectly - thanks!

**Comment by Cellphone70** [comment]
I was using the docker version experiencing the issue.  I abandoned that, and compiled from the ditros about 2 weeks ago, and Phase 2 has been working for me since.

**Comment by jonk6** [comment]
> Recompiled on 6/13 and it's not working perfectly - thanks!

not? Or now?

**Comment by mikewren** [comment]
> > Recompiled on 6/13 and it's not working perfectly - thanks!
> 
> @mikewren - not? Or now?

Sorry, typo, it's NOW working perfect - https://openmhz.com/system/monroecony
