### ISSUE TITLE
Missing dependencies MacOS

### ISSUE THREAD

**Issue by nhasler** [robotastic/trunk-recorder#32]
In file included from /Users/r00t/trunk-recorder/recorder.h:29:
/Users/r00t/trunk-recorder/dsd_block_ff.h:25:10: fatal error: 'dsd/dsd_api.h'
      file not found
#include <dsd/dsd_api.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/recorder.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/recorder.dir/all] Error 2
make: *** [all] Error 2

**Comment by robotastic** [comment]
Sorry about that! I removed the needed for DSD, but I guess I didn't remove all the references. I didn't catch this one. Should be good now
