### ISSUE TITLE
Missing Dependency MacOS decoder_bf.h

### ISSUE THREAD

**Issue by nhasler** [robotastic/trunk-recorder#34]
n file included from /Users/r00t/trunk-recorder/main.cc:34:
/Users/r00t/trunk-recorder/p25_trunking.h:52:10: fatal error: 
      'op25/decoder_bf.h' file not found
#include <op25/decoder_bf.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/recorder.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/recorder.dir/all] Error 2
make: *** [all] Error 2

**Comment by nhasler** [comment]
Everything builds nice on OSX after that line is removed.

**Comment by robotastic** [comment]
Awesome! The latest version of Master should have that fixed
