### ISSUE TITLE
Upgrade receiver?

### ISSUE THREAD

**Issue by JustApu** [robotastic/trunk-recorder#354]
I'm currently monitoring two sites from the [New Jersey Interoperability Communications System](https://www.radioreference.com/apps/db/?sid=7021) and it works okay with seven RTL dongles. But I suspect I can do better. The question is how.

The most obvious flaw is that I'm limited by the number of digitalRecorders per dongle.

One of the two sites decodes well; the other site wavers sometimes. I suspect that maybe the receiver sensitivity or the antennae is the culprit.

Is an Airspy R2 or Airspy Mini going to help or hurt? Money better spent on separating the two sites into two completely separate instances of trunk-recorder (which probably means more RTL dongles & another USB hub, or an entirely separate computer)?

Other thoughts?

[trunk-recorder_config.txt](https://github.com/robotastic/trunk-recorder/files/4605797/trunk-recorder_config.txt)

**Comment by robotastic** [comment]
I am not sure if things would change too much with a better SDR. Better antennas and cabling could be a good place to start. I also got a USB powered fan to point at my RTLSDRs and that has seemed to help them last longer. It could be that a few of them are dieing from heat. You should be able to run as many digitalRecorders as you want. They really only take up CPU time when they are actively recording.
