### ISSUE TITLE
Add title tag to m4a files?

### ISSUE THREAD

**Issue by dmonies327** [robotastic/trunk-recorder#369]
Is it possible to add a title tag to the m4a files created when uploading to openMHZ/broadcastify calls? I'd like to use these files with liquidsoap to stream to broadcastify as they are already balanced/normalized well, and there's no need to repackage the wav to mp3 just to add title comments if liquidsoap can play/stream the m4a/aac files (assuming this can also be done). I'd like them to have the TITLE tag on them, however.
If this isn't practical, does anyone know a good utility to quickly add the tag to the file that could be run in a separate script (similar to the way the encode_upload.sh does in the TR/LiquidSoap wiki writeup on RR)? I tried using id3v2 to add it, but it appears to just corrupt the files.
EDIT: I believe I found that I should be using mutagen to do this, but the original question still stands as to if trunk-recorder already has this functionality.

**Comment by EricTendian** [comment]
There isn't that functionality currently available within trunk-recorder itself, since in https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/uploaders/call_uploader.cc#L20 we are just converting the wav to a m4a. However, it looks like fdkaac does have an argument `--title` so it probably would be possible to modify the upload logic to include whatever alpha tag is associated with the talkgroup if it exists.

**Comment by robotastic** [comment]
This is a good idea and should be a pretty easy change. I will add this to my list of things.

**Comment by natecarlson** [comment]
What content do you want in the tag?

Or in the ideal world should it be configurable, with placeholders for each of the major variables?

**Comment by dmonies327** [comment]
The alpha-tag associated with the talk group would be ideal, but
configurable might be more flexible for the community.

**Comment by robotastic** [comment]
I really have to add this - I thought I did at one point but I don't see it in the code

**Comment by kd4e** [comment]
> I really have to add this - I thought I did at one point but I don't see it in the code

:+1:

**Comment by robotastic** [comment]
Ok - it looks like it is working. It is in the dev/backlog branch, and will be merged in soon. Eventually I will look at how to create custom sox / ffmpeg so you can change parameters around.
