### ISSUE TITLE
Anyone know what "output_index must be < noutputs" means?  Getting this error on the latest build.. not sure what im doing wrong.. Any ideas where to look?

### ISSUE THREAD

**Issue by tdduarte** [robotastic/trunk-recorder#414]
terminate called after throwing an instance of 'std::out_of_range'
  what():  output_index must be < noutputs
Aborted (core dumped)

Moved Modulation and squelch to  systems..

Thanks!

**Comment by robotastic** [comment]
That probably means I messed something up... can you share your config file? I will try running it and see what is causing the crash.

**Comment by tdduarte** [comment]
{
    "ver": 2,
    "sources": [{
        "center": 453550000,
        "rate": 2048000,
        "error": 0,
        "gain": 60,
        "debugRecorders": 0,
	"digitalRecoders": 1,
        "driver": "osmosdr",
	"device": "rtl=01"
}, {
        "center": 460100000,
        "rate": 2048000,
        "error": 0,
        "gain": 60,
        "debugRecorders": 0,
        "analogRecoders": 3,
        "driver": "osmosdr",
        "device": "rtl=02"
 }
 ],
    "systems": [
        {
            "type": "conventionalP25",
            "channels": [453550000],
            "shortName": "dartmouthP25",
            "apiKey": "",
            "talkgroupsFile": "dartmouthp25.csv",
            "broadcastifyApiKey": "",
	    "broadcastifySystemId": "",
            "callLog": true,
	    "digitalLevels": 14,
            "audioArchive": false,
            "modulation": "fsk4",
            "squelch": -30,
            "minDuration": 0
}, {
            "type": "conventional",
            "channels": [460287500, 460087500, 460062500],
            "shortName": "dartmouthfd",
            "apiKey": "",
            "talkgroupsFile": "dartmouthfd.csv",
            "broadcastifyApiKey": "",
	    "broadcastifySystemId": "",
            "callLog": true,
            "audioArchive": true,
            "minDuration": 3,
            "squelch": -30,
            "decodeMDC": true
}
],
  "uploadServer": "https://api.openmhz.com",
	"broadcastifyCallsServer": "https://api.broadcastify.com/call-upload",
	"controlWarnRate": 5,
	"callTimeout": 0.75

}

**Comment by robotastic** [comment]
Thanks - It looks like there is problem with P25 Conventional in FSK4 mode. I will go see if I can sort it out quick.

**Comment by tdduarte** [comment]
OK great thank you!

**Comment by robotastic** [comment]
OK - so I think the latest commit should fix... or atleast stop it from crashing. I couldn't test if it is recording correctly. Let me know if it works.

**Comment by tdduarte** [comment]
looks good now! Thank you for the quick fix!

**Comment by Cole0209** [comment]
I just saw this issue after I made mine. It looks like something is still up with the conventional p25 recording. @tdduarte Are you seeing any issues with your traffic being split into 5-6 second files? #415

**Comment by tdduarte** [comment]
@Cole0209 you maybe right.. I seem to be getting all the transmissions but yea nothing over 6 secs

**Comment by tdduarte** [comment]
Analog seems fine

**Comment by tdduarte** [comment]
P25 clips at 6 secs then starts a new file for sure seen a few mid transmission. Analog seems to be fine

**Comment by robotastic** [comment]
I figured out a way to test locally - I am just using the channels of a trunking system as P25 Conventional. I am seeing the same thing. Weird! I will add in lots of print statements and get to the bottom of this. For some reason I think the squelch may not be working right...

**Comment by robotastic** [comment]
OK! Well, I forgot the Squelch block in P25 Recorder. I just tested and... NOW it should be working. Let me know though, clearly I mess this up a bit.

**Comment by tdduarte** [comment]
Looks good here now no more clipping... Just need to play with the gain and squelch setting for the analog side but happy i can now do analog and p25 on one source.   Thank you for all your efforts with this project!

**Comment by Cole0209** [comment]
@robotastic After these changes it looks like the P25 radio ids don't reset with every transmission. I had one 5 second transmission with 90+ radio ids attached... Restarting trunk recorder seems to reset the count.

**Comment by robotastic** [comment]
Agh! yep, when I got rid of the seperate recorder for P25 conventional calls it got rid of reseting the source list for each new recording. added that back in. Thanks for putting up with all the bugs and reporting them!

**Comment by robotastic** [comment]
I think we solved this. Please reopen if not.
