### ISSUE TITLE
decodeMDC no longer works

### ISSUE THREAD

**Issue by Cole0209** [robotastic/trunk-recorder#419]
I noticed after the recent changes were made to conventional recorders decoding of MDC tones for the radio ID no longer works on standard conventional audio. Looking back in my systems it may have happened around the same time issues were being had with conventional P25 radio ids from issue #414. I don't have any systems using the other decode types so I am unsure if those have also stopped working

**Comment by JoeGilkey** [comment]
I've checked in a fix for this. The new adjustable sample rate on outputs needed to be passed into the decoder.

**Comment by robotastic** [comment]
Thanks @JoeGilkey  I have merged in the PR. @Cole0209 let us know if that does the trick. I don't have a local system to test with.

**Comment by Cole0209** [comment]
Yup looks like that fixed it!
