### ISSUE TITLE
Airspy R2 Rate problem

### ISSUE THREAD

**Issue by rpdale** [robotastic/trunk-recorder#431]
Using gqrx I can select 2.5M, 3M, 6M, or 10M rates. Trunk-recorder only allows 2.5M and 10M. Any idea how to enable those other two options?

 - Rob

**Comment by gonzoblue** [comment]
I have an airspy mini and have been able to use 6M and 3M, haven't tried any others. Just info, not sure if it helps anything.

**Comment by leee** [comment]
What was trunk-recorder doing/reporting that didn't allow for 3 or 6 Msps? It seems like this other user can do it, so I think this issue can be closed for now (@robotastic) - but if you have any error messages/logs to share definitely open this issue up again.

**Comment by robotastic** [comment]
Agreed - Trunk Recorder should allow for any value to be passed through to the driver. Let me know if there is a deeper issue though.
