### ISSUE TITLE
libcurl4-openssl-dev vs libcurl4-gnutls-dev (Question)

### ISSUE THREAD

**Issue by alphafox02** [robotastic/trunk-recorder#432]
I notice that when following the 20 series guide that my already installed libcurl4-gnutls-dev is uninstalled and replaced with libcurl4-OpenSSL-dev. I do get a successful compile and at a quick glance it seems trunk recorded is available on 20.04, haven’t tested against a config file. 

My question is, because I’m assuming I had libcurl4-gnutls-dev installed for a reason, can trunk recorded work with it or do I need to have the OpenSSL version installed? 

After reading a few forums it sounds like they both can’t be installed at the same time and some things need gnults vs OpenSSL.

**Comment by robotastic** [comment]
I don't think we have any preference either way and it should work with both. Let me know if we need to change something though
