### ISSUE TITLE
Log directory should be configurable

### ISSUE THREAD

**Issue by robbiet480** [robotastic/trunk-recorder#443]
[The log directory should be configurable](https://github.com/robotastic/trunk-recorder/blob/a6e4a8df83e89c7203fa07749f63c41cd682c2c6/trunk-recorder/main.cc#L1463).

**Comment by rosecitytransit** [comment]
Related to this, can the log files match the console output and include the severity level of the messages?

**Comment by rosecitytransit** [comment]
Also, a workaround is to move the log directory and then replace it with a symbolic link.

**Comment by rosecitytransit** [comment]
> Related to this, can the log files match the console output and include the severity level of the messages?

I addressed this in #441 with this commit 689e17a01d17bbce947a706d899d0700cebc9acb
