### ISSUE TITLE
Allow user to specify gain names.

### ISSUE THREAD

**Issue by jnse** [robotastic/trunk-recorder#489]
My USRP has gain levels not supported by the hardcoded gain names in trunk-recorder (BBG and GC1).
It would be preferable if the gain name could be user-specified.

**Comment by robotastic** [comment]
Happy to check it out - what is the name of the Gain Stage for the USRP? I will have to check with the USRP code to see how the different types of gain are set... it has been a while since I messed with it.

**Comment by jnse** [comment]
Mine has "GC1" and "BBG" as gains, but my point was you should be able to pass arbitrary names like the op25 rx.py lets you do via the -N argument (eg: ./rx.py -N 'GC1:48,BBG:3' ...) - so the op25 rx.py implementation might be useful as a reference.
