### ISSUE TITLE
ChanList and the config option should be called the same thing

### ISSUE THREAD

**Issue by thefinn93** [robotastic/trunk-recorder#49]
Seems to me that `talkgroups.csv` is expected to be there, but not committed to git nor is it in `.gitignore`. Is there some reason it isn't in gitignore?

**Comment by robotastic** [comment]
ChanList.csv is actually the talkgroups.csv file. I should probably rename it and include it as talkgroups.csv.sample. Would that make it less confusing?

**Comment by thefinn93** [comment]
ChanList is *a* `talkgroups.csv`-format file? Or is the thing specified in my in my `config.json` unused? I'm confused

**Comment by robotastic** [comment]
Sorry just noticed I dropped the thread. ChanList is a talkgroups.csv formatted file. I should go through and align the filename and the config name.
