### ISSUE TITLE
AACOFD trouble

### ISSUE THREAD

**Issue by jdhankins28** [robotastic/trunk-recorder#492]
AACOFD’s stream is pushing through the recordings with no audio playing, can anyone assist. I am not the owned

**Comment by robotastic** [comment]
I have been trying to work with the person running it for a bit to get things fixed. I will go check in with them and see if they made progress. If you are in the Anne Arundel area and want to try setting up a system, I can help you get started.

 - Luke

**Comment by kcwebby** [comment]
This should be fixed now.

Thanks.

**Comment by leee** [comment]
@jdhankins28 (or @robotastic ) this issue can be closed.
