### ISSUE TITLE
Allow upload of different talkgroups to different OpenMhz systems

### ISSUE THREAD

**Issue by bab5871** [robotastic/trunk-recorder#498]
I guess this is more of an enhancement/feature request. Currently you can define a system and upload talkgroups to a single OpenMHZ system. In the interest of reducing the number of SDR dongles required it would be awesome to be able to split a system to upload to multiple places.  

For example I currently run a stream to broadcastify/openMhz of a specific subset of talkgroups for Fire/EMS. I would additionally like to process other talkgroups from the same system and upload them to a separate Police/Sheriff feed for broadcastify/OpenMhz. 

It seems this is possible for at least Broadcastify via some modifications of the scripts used as documented [here](https://wiki.radioreference.com/index.php/Streaming_with_Trunk_Recorder_and_Liquidsoap#Improved_Multiple_Stream_Support). It would be great to have this ability with OpenMhz uploads as well with the intended goal being to not have to add more SDR dongles to a system if possible.

**Comment by ratmandu** [comment]
This could probably be done pretty easily with an external upload script.
I've got one that I use for uploading the same file to multiple OpenMHZ instances here: https://github.com/ratmandu/trunk-recorder-multi-uploader

I don't think it would be too hard to add some logic to check the talkgroup before upload, and choose the endpoint to upload to based on that.
