### ISSUE TITLE
Unable to build on Arch Linux

### ISSUE THREAD

**Issue by bijan588** [robotastic/trunk-recorder#510]
Hi,
I'm stuck here.

I am unable to build any of the trunk-recorder versions including the beta.

Initially I got an error and found a report on here about it being from a new version of GNURadio. Downgraded to 3.8 but still unable to build, this time further along in the make it crashes.  All dependencies are installed.

`  In file included from /home/bijan/Downloads/trunk-recorder-4.0-beta-3/trunk-recorder/recorders/analog_recorder.h:47,
                 from /home/bijan/Downloads/trunk-recorder-4.0-beta-3/trunk-recorder/source.h:11,
                 from /home/bijan/Downloads/trunk-recorder-4.0-beta-3/trunk-recorder/source.cc:1:
/home/bijan/Downloads/trunk-recorder-4.0-beta-3/trunk-recorder/recorders/recorder.h:38:10: fatal error: gnuradio/filter/rational_resampler_base.h: No such file or directory
   38 | #include <gnuradio/filter/rational_resampler_base.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/trunk_recorder_library.dir/build.make:90: CMakeFiles/trunk_recorder_library.dir/trunk-recorder/source.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:234: CMakeFiles/trunk_recorder_library.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

I've searched but I can't find anything. Any ideas?

**Comment by robotastic** [comment]
I think I have some homework to do - This sounds related to #459 . I think I have to setup a few different Dockerfile to try out builds on different OSs.

**Comment by robotastic** [comment]
I have had a chance to test with gnuradio 3.9 yet, but I did improve the compile process for Ubuntu 21.04. Can you give the branch `4.0-beta` a try?

**Comment by toddejohnson** [comment]
There is an aur for this: https://aur.archlinux.org/packages/trunk-recorder-git

Although I haven't been able to get it working just yet it is building

**Comment by robotastic** [comment]
This should be fixed on the `4.0-beta` branch. Going to close for now, but please re-open if new problems crop up.
