### ISSUE TITLE
[Idea] Make a Community Driven Config Repo

### ISSUE THREAD

**Issue by MaxwellDPS** [robotastic/trunk-recorder#512]
@robotastic I'm curious what you would think of setting up a repo where people can share Trunk recorder configs for their local sites, to create a scanner type database?

**Comment by robotastic** [comment]
This is a great idea! To keep things simple, I will just start a Github Repo along with a description document that has a table explaining each config, along with a link to the file, and the RR entry. I will start doing that with all of the examples included in Trunk Recorder. People can make a Pull Request to add additional entries. I will also create a folder for help/upload scripts too.

**Comment by Dygear** [comment]
@MaxwellDPS was this ever completed?

**Comment by MaxwellDPS** [comment]
@Dygear sorry It took me a sec, but yest indeed! https://github.com/robotastic/trunk-recorder-configs/pull/1/files
