### ISSUE TITLE
unitScript functionality doesn't seem to be working in 4.0-beta

### ISSUE THREAD

**Issue by aaknitt** [robotastic/trunk-recorder#525]
unitScripts specified in config.json that fire and function correctly in 3.3.7 don't appear to fire in 4.0-beta.

config.json:
```
{
	"ver": 2,
    "sources": [{
        "center": 853175000,
		"ppm":0,
        "rate": 1400000,
        "gain": 40,
        "digitalRecorders":2,
        "driver": "osmosdr",
		"device": "rtl=0"
    }],
    "systems": [{
        "control_channels": [853712500,853687500,853350000,853137500],
        "type": "p25",
		"modulation": "qpsk",
		"digitalLevels":8,
		"shortName": "oasiswauk",
		"talkgroupsFile": "OASISTG.csv",
		"unitScript":"unitscript.py",
		"recordUnknown": false,
		"audioArchive": true,
		"talkgroupDisplayFormat": "id_tag"
    }],
	"minDuration": 0,
	"defaultMode": "digital",
	"captureDir": "/home/pi/tr-recordings",
	"controlWarnRate":10,
	"controlWarnUpdate":1,
	"frequencyFormat": "mhz",
	"logFile": true,
	"callTimeout": 2,
	"statusAsString": true
}
```
minimal test script unitscript.py:
```
#!/usr/bin/python3
print("THIS IS A UNIT SCRIPT")
```
Results in 3.3.7:
![image](https://user-images.githubusercontent.com/13441553/136576208-b90fa108-508b-4cf0-a6f3-77296c3e7a33.png)

No evidence of script being run in 4.0-beta:
![image](https://user-images.githubusercontent.com/13441553/136576384-4096b9f3-e46c-41b4-950a-e590072e214d.png)

**Comment by robotastic** [comment]
Ok - this commit ba6959fc655cc70272506e7cd9e62f2d7798c8fc should fix the unitScript issues. Let me know if that doesn't work.

**Comment by rosecitytransit** [comment]
I know this is way later (I've just been letting t-r run), but the "./" should be in your config.json entry as `"unitScript":"./unitscript.py",` I thought I noted that in the documentation I wrote; it's just like if you were to execute the script on the command line.. `./` would be incorrect if the script is somewhere else besides the same directory as trunk-recorder.
