### ISSUE TITLE
4.0 build fails on Fedora, linking error

### ISSUE THREAD

**Issue by mldulaney** [robotastic/trunk-recorder#529]
/usr/bin/ld: libgnuradio-op25_repeater.so: undefined reference to `imbe_vocoder::imbe_vocoder()'
/usr/bin/ld: libgnuradio-op25_repeater.so: undefined reference to `imbe_vocoder::decode(IMBE_PARAM*, short*, short*)'
/usr/bin/ld: libgnuradio-op25_repeater.so: undefined reference to `imbe_vocoder::clear()'
/usr/bin/ld: libgnuradio-op25_repeater.so: undefined reference to `imbe_vocoder::encode(IMBE_PARAM*, short*, short*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/trunk-recorder.dir/build.make:744: trunk-recorder] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/trunk-recorder-4.0/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/trunk-recorder.dir/all] Error 2
gmake[1]: Leaving directory '/builddir/build/BUILD/trunk-recorder-4.0/redhat-linux-build'
gmake: *** [Makefile:139: all] Error 2

**Comment by mldulaney** [comment]
That built on f35, thanks!  Might could you do a 4.1 release to make my life a teensy bit easier?

**Comment by robotastic** [comment]
That is a pretty dense error! I don't think I will be able to dive into it. If you are able to figure out what changes are necessary to fix it, I would totally accept a PR on it. Right now, I think the best option for packaging on Fedora is to use the Docker image. It is a lot easier for me to support.
