### ISSUE TITLE
Smartnet Radio ID Issue

### ISSUE THREAD

**Issue by dreinhold** [robotastic/trunk-recorder#53]
I just noticed my last commit de5942c9d was grabbing the radio id from the last message.source.
The issue is message.source has its least significant byte removed (well set to 0) as that is the status byte when it's the channel id.
I have a patch I'll submit tomorrow, just wanted to open this if anyone one else is using the latest version and notices some duplicate radio ids on a smartnet system.

**Comment by robotastic** [comment]
I just merged in the change. Thanks for submitting, and catching this!
