### ISSUE TITLE
"call" events not being passed to unitScript - 4.0

### ISSUE THREAD

**Issue by aaknitt** [robotastic/trunk-recorder#531]
unitScript is seeing "join", "off","ackresp","on" events but no "call" events.  I added the function below to unit_script.cc and it's working but am not submitting a pull request because it has the following issues:

- source_id is always reporting 0.  Not sure why get_current_source_id() isn't providing good info.  As a band-aid I disabled the check against source_id being zero for testing (as reflected below).  
- Behavior seems slightly different than in the past.  With this function added to unit_script.cc, a "call" fires the unitScript when a recorder is started.  In the past, I believe that the unitScript would fire for all calls on the system, regardless of whether trunk-recorder was actually recording it or not.  The new behavior is fine for my specific application but perhaps there's a better way to implement than what I started doing in order to maintain reverse compatibility.  

```
int call_start(Call *call) {
    long talkgroup_num = call->get_talkgroup();
    long source_id = call->get_current_source_id();
    //BOOST_LOG_TRIVIAL(info) << "CALL for TGID " << talkgroup_num <<" and source ID " << source_id;
    std::string short_name = call->get_short_name();
    std::string system_script = get_system_script(short_name);
  //if ((system_script != "") && (source_id != 0)) {
  if ((system_script != "") ) {
    char shell_command[200];
    sprintf(shell_command, "./%s %s %li call %li &", system_script.c_str(), short_name.c_str(), source_id, talkgroup_num);
    int rc =  system(shell_command);
    return 0;
  }
    return 1;
}
```

**Comment by robotastic** [comment]
I YOLO'ed and just changed things so that the plugin hooks now get called for all Calls, even ones that are not recorded. The call_start() will also be called eveytime there is a change of source ID
