### ISSUE TITLE
alphatags information is not available in json

### ISSUE THREAD

**Issue by ZeroChaos-** [robotastic/trunk-recorder#537]
when I specify "alphatags": ["FRS 15"] or similar, the alpha tag doesn't show up in the log or the json file.  Am I doing this wrong?  Or is this information not used at this time?  It would be super incredibly helpful for this information to be used in the log and json file.

**Comment by robotastic** [comment]
hmm... I just went and checked and the code is in there to print out a tag:
https://github.com/robotastic/trunk-recorder/blob/a8a7b065e4ac5bcee05cfb18946e2026d17b89f0/trunk-recorder/call_concluder/call_concluder.cc#L77

Is it just not printing out the Tag for a src even when it is set in the file?

I am trying to figure out if I need to debug code or add a new feature. I have actually never used the Alpha Tagging, so I guess I should try spinning up a file.

**Comment by ZeroChaos-** [comment]
Unit tags show up, but frequency tags do not.

```
{
"freq": 460050000,
"start_time": 1636236886,
"stop_time": 1636236896,
"emergency": 0,
"encrypted": 0,
"call_length": 10,
"talkgroup": 1,
"freqList": [{ "freq": 460050000, "time": 1636236886, "pos": 0.0, "len": 10, "error_count": 0.0, "spike_count": 0.0}],
"srcList": [ {"src": 1542, "time": 1636236886, "pos": 0, "emergency": 0, "signal_system": "", "tag": "Moon PD 606"} ]
}
```

**Comment by robotastic** [comment]
ohh!!! yea, I totally confused unitTags and alphaTags. ok, Let me go check and see what I can do.

**Comment by robotastic** [comment]
Ok - I just committed a change that I think should add a new key to the JSON called talkgroup_tag, that should have this info. Let me know if this is what you were thinking.

**Comment by ZeroChaos-** [comment]
```
{
"freq": 460050000,
"start_time": 1636340101,
"stop_time": 1636340121,
"emergency": 0,
"encrypted": 0,
"call_length": 20,
"talkgroup": 1,
"talkgroup_tag": Moon Police,
"freqList": [{ "freq": 460050000, "time": 1636340101, "pos": 0.0, "len": 20, "error_count": 0.0, "spike_count": 0.0}],
"srcList": [ {"src": 1545, "time": 1636340101, "pos": 0, "emergency": 0, "signal_system": "", "tag": "Moon PD 609"} ]
}
```

Yup, that's everything I wanted.  Thanks!

**Comment by ZeroChaos-** [comment]
whoops, I spoke too soon.  It would be great if it were valid json, you need the quotes around the string

**Comment by taclane** [comment]
Yeah, the invalid json is breaking some stuff downstream like the rdio-scanner importer.

Adding quotes in call_concluder.cc gets the API working agin.
`    json_file << "\"talkgroup_tag\": \"" << call_info.talkgroup_tag << "\",\n";
`

**Comment by ZeroChaos-** [comment]
heh, yeah, that's how I noticed at first too.  It's been very quiet in my office today.

**Comment by robotastic** [comment]
Whoops! ok, I think I pushed a fix... I will do dev on a separate branch next time

**Comment by ZeroChaos-** [comment]
fixed, <3
