### ISSUE TITLE
unknown caller difference in json between 3.x and 4.x

### ISSUE THREAD

**Issue by ZeroChaos-** [robotastic/trunk-recorder#541]
4.x
```
{
"freq": 470437500,
"start_time": 1635047334,
"stop_time": 1635047344,
"emergency": 0,
"encrypted": 0,
"call_length": 9,
"talkgroup": 1,
"freqList": [{ "freq": 470437500, "time": 1635047334, "pos": 0.0, "len": 9, "error_count": 0.0, "spike_count": 0.0}],
"srcList": [ {"src": 0, "time": 1635047334, "pos": 0, "emergency": 0, "signal_system": "", "tag": ""} ]
}
```

3.x
```
{
"freq": 4.64025e+08,
"start_time": 1635347548,
"stop_time": 1635347554,
"emergency": 0,
"duplex": 0,
"mode": 0,
"priority": 0,
"call_length": 5.35675,
"talkgroup": 1,
"srcList": [  ],
"freqList": [ ]
}
```

**Comment by ZeroChaos-** [comment]
After considering this for a while, I think the 3.x behavior is better.  in 4.x it is not possible to determine if no unit identifier was seen, or if the unit identifier of 0 was seen.

**Comment by robotastic** [comment]
The one advantage of the 4.0 approach is that you can see that a different transmitter was detected, even if a source ID frame didn't come in time. What if I set the Source ID to be -1 when it is unknown? Is 0 ever used for a Source ID? I honestly haven't paid too much attention to it, some systems may be.

**Comment by ZeroChaos-** [comment]
as far as I know, 0 is valid.  -1 isn't, again, as far as I know.  So if you want to use -1 I'm also fine with that.  I just want to know the difference between "I saw nothing" and "I saw uid 0"

**Comment by taclane** [comment]
> Is 0 ever used for a Source ID? 

A P25 Unit ID of 0 is technically in the in the range of $000000-$FFFFFF, but it's the default value for an unconfigured radio and shouldn't be seen on a live system.  At least in the US, public safety interoperability standards remind P25 users that $000000 is "never associated with a radio unit".  https://www.cisa.gov/publication/fog-documents

If not just leaving the field null, UID 0 is likely safe enough to use for unidentified transmitters. It may also be hard to gauge what pushing a negative UID downstream might do in each of the different broadcasting/sharing platforms.

**Comment by ZeroChaos-** [comment]
I would say you made the opposite case.  The fact that 0 should never be used is exactly why it is important to detect when it is used.

**Comment by taclane** [comment]
Sure. But from the standpoint of data collection or streaming, either a null UID or a 0 would be preferable to a negative UID.  Outside of perhaps DEFCON, $000000 is not a UID you would encounter in the wild.

**Comment by ZeroChaos-** [comment]
I don't mean to be a broken record, but again you make the opposite case.  You *shouldn't* see that uid, but that's exactly the point of why it is important to notice it.  One time I rented radios and specifically said I needed the radios to have unique uids, and still got every single radio programmed with the same uid..... mistakes happen, failing to detect them is inexcusable.

Now, I do agree that if the address space starts at 0 that something might attempt to validate it and leaving source blank is an acceptable solution instead of providing an invalid uid.  I'm still fine with empty or -1, but I'm very unhappy using a valid uid as "I saw nothing".

**Comment by robotastic** [comment]
@ZeroChaos - can you try out the `op25-update` branch? I added in -1 being the src id when it is unknown.

**Comment by ZeroChaos-** [comment]
I tested on the trbo-support branch and the uid is set to -1 when unknown.  this is useful and desirable.  it works with my player code (no one cares) and also with rdio scanner without error.

Unfortunately, the default TID seems to have gone from "1" to "ffffffffffffffff".  I mostly have analog, and it is especially wild to see the analog channels all tagged as TID 0xffffffffffffffff.  Pretty please don't do that.  Analog channels can be 1 (as they were, it really doesn't matter) or -1 (if you want to repeat the pattern) and for digital the tid should probably always be known?

I think it's sane to repeat the "-1 means unknown" pattern for the tid, but I'm not sure how your internal handling all works for the analog channels so it's your discretion as to if that's better or worse.

**Comment by robotastic** [comment]
Weird - is this for Analog recorders or all types of recorders? Is this showing up in the JSON or the logs or both? and TID means Talkgroup ID, right? Is this referring to the number that represents the channel, or the bit of text?  Just trying to find where the bug is so I can fix it. This wasn't an intentional change.

**Comment by ZeroChaos-** [comment]
I only have conventional recorders but I can confirm this happens in the trbo-support branch for both conventional and conventionalDMR

**Comment by robotastic** [comment]
Could you share a copy of the logs or JSON where this is happening? I am still confused on exactly where it is cropping up.

**Comment by ZeroChaos-** [comment]
crap, sorry, I dug into it and it's my fault.  my encode-upload.sh script converts -1 to hex and it's all f's.  This is all working correctly on your end and when this is merged into master (not sure if it is since I'm on the trbo branch) then this can be closed.  Thanks!

**Comment by taclane** [comment]
Just as a heads-up, there's something about a -1 UID that seems to be causing trouble for rdio-scanner 6.x (the previous 5.2 branch was unaffected).

I'll let rdio-scanner know too, but a -1 UID may display as all 0xFFs in the web interface, or even soft lock the native app because it is unable to load the call.
![IMG_2695](https://user-images.githubusercontent.com/12748062/146702561-40b32db0-81a9-4442-ac35-fab1e3714466.PNG)

**Comment by ZeroChaos-** [comment]
ugh, my lazy self is on 5.x still so I didn't notice this.

I opened a bug for rdio-scanner since I didn't see one https://github.com/chuot/rdio-scanner/issues/73

**Comment by taclane** [comment]
I'll have to check, it could even be on the trunk-recorder end.  

I've also been trying out the new rdioscanner_uploader plugin (which requires 6.x), and somewhere along the way it looks like the -1 UID is bumping into an unsigned long int.

**Comment by taclane** [comment]
Seem like trunk-recorder or the new plugin isn't the issue
` [{ "pos": 0.00, "src": -1 }]` 
goes out over the plugin, or
`"srcList": [ {"src": -1, "time": 1639954699, "pos": 0, "emergency": 0, "signal_system": "", "tag": ""} ]`
goes out via an upload script.

Rdio-scanner has this in the db:
<img width="214" alt="db" src="https://user-images.githubusercontent.com/12748062/146776760-44347519-028f-4907-b673-d113d3494ce1.png">

I'll update the ticket on that end.  Back before I tried 6.0, it didn't appear to have an issue with -1 sources.
<img width="208" alt="db2" src="https://user-images.githubusercontent.com/12748062/146777432-cfa4a4c5-8450-44db-9763-03ecd8650ba5.png">

**Comment by chuot** [comment]
FYI, v6.1 will have a fix for this.

**Comment by ZeroChaos-** [comment]
This is all fixed in TR and in rdio_scanner.  If anything else is broken then new bugs should be opened for the appropriate things but I'm very happy here.  Thanks!

**Comment by rosecitytransit** [comment]
Just as an FYI, I've noticed `src_id > 0` in places the code which would affect handling of Unit IDs of 0.
