### ISSUE TITLE
Zello support

### ISSUE THREAD

**Issue by lbttim** [robotastic/trunk-recorder#542]
HI,
is it possible to add zello as listening service?
https://github.com/zelloptt/

**Comment by rml596** [comment]
This is probably best done via an upload script.
https://github.com/robotastic/trunk-recorder/tree/master/plugins/unit_script

**Comment by robotastic** [comment]
This is a great idea! I don't have the cycles to take it on, but the Plugin system or the Upload Script would be a great way to add it. I will this open for a little to see if there are folks that would want to contribute to working on this.

**Comment by aaknitt** [comment]
For real time streaming, the audio_stream() function in a plugin looks like it would be ideal for this, but I'm having some issues with it  at the moment (see gitter chat).  Here's some reference Python code for sending streaming audio to Zello:

https://github.com/aaknitt/zellostream

An uploadScript could also work but it wouldn't be quite real time.

**Comment by kb2ear** [comment]
Nothing in trunk-recorder is real time

**Comment by aaknitt** [comment]
I have this working using the new [simplestream plugin](https://github.com/robotastic/trunk-recorder/blob/master/docs/CONFIGURE.md#simplestream-plugin) and the zellostreamUDP.py script that I've added here:

https://github.com/aaknitt/zellostream

@kb2ear this is near-real time streaming.  The plugin system sends the audio as it's being recorded.   There is some latency of course, but no waiting for the recording to be done and then uploading.

**Comment by Dygear** [comment]
This can be closed and this is amazing work @aaknitt!
