### ISSUE TITLE
Smartnet skipping talkgroups

### ISSUE THREAD

**Issue by dreinhold** [robotastic/trunk-recorder#56]
Is there a technical reason to skip talkgroup IDs 56016 and 8176.
In smartnet_parser.cc https://github.com/robotastic/trunk-recorder/blob/4e5a8b4647e420fd987f8c08fe70229fd8a56873/smartnet_parser.cc#L59

The comment makes it sound like it was something just for a specific system, and maybe should be removed?

**Comment by robotastic** [comment]
Nope! That was an old remnant from a radio system that is now offline.  I just removed it. Good Call
