### ISSUE TITLE
Add Tetra support

### ISSUE THREAD

**Issue by JoeGilkey** [robotastic/trunk-recorder#563]
Add support for Tetra as provided by the OP25 group. Now that Tetra has received FCC approval, many transit and data centric agencies are jumping on board.

Care should be taken on 700MHz frequencies. The individual subscriber radios can be switched to P25 mode at any point (user selectable) on the same frequency.

**Comment by robotastic** [comment]
Prob not going to support Tetra, unless there is a lot of interest from the community and an implementation I can work off of
