### ISSUE TITLE
Broadcastify upload fails - metadata error

### ISSUE THREAD

**Issue by gonzoblue** [robotastic/trunk-recorder#580]
After updating to the latest version as of today (12/14/21), uploading to Broadcastify fails with a metadata error.

A fix is mentioned in the gitter chat by @taclane:

trunk-recorder/call_concluder/call_concluder.cc
Change line 69 to:
`json_file << "\"audio_type\": \"" << call_info.audio_type << "\",\n";`

**Comment by robotastic** [comment]
It should be fixed in the latest version... sorry about that!

**Comment by e850205** [comment]
That did not fix it.

**Comment by robotastic** [comment]
@e850205 - can you provide more information?
