### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Dewey3** [robotastic/trunk-recorder#599]
I'm hoping this is just a burp in the internet connect, but multiple attempts to install the libraries for the Raspberry Pi are resulting in:

E: Unable to locate package libusb-1.0-0.dev
E: Couldn't find any package by glob 'libusb-1.0-0.dev'

EDIT:  Just an update to my own post, doing an apt search on libusb-1.0-0.dev is returning libusb-1.0-0-dev (a hyphen replacing the period before the "dev" at the end).  Is it possible that this is a new name for libusb-1.0-0.dev?

**Comment by promyvion** [comment]
Encountering the same issue! Did your period/hyphen swap idea pan out?

**Comment by Dewey3** [comment]
> Encountering the same issue! Did your period/hyphen swap idea pan out?
> 
> EDIT: I tried it myself. Swapping a period for a hyphen let me install it just fine, so it appears the instructions are indeed out of date.

Yes, replace the period with a hyphen and the install will continue.

**Comment by bctrainers** [comment]
> Encountering the same issue! Did your period/hyphen swap idea pan out?
> 
> EDIT: I tried it myself. Swapping a period for a hyphen let me install it just fine, so it appears the instructions are indeed out of date.

Which page did you use for install/compile guidance?

**Comment by promyvion** [comment]
> > Encountering the same issue! Did your period/hyphen swap idea pan out?
> > EDIT: I tried it myself. Swapping a period for a hyphen let me install it just fine, so it appears the instructions are indeed out of date.
> 
> Which page did you use for install/compile guidance?

I was using the [Raspberry Pi instructions.](https://github.com/robotastic/trunk-recorder/blob/master/docs/INSTALL-PI.md)

**Comment by robotastic** [comment]
Just fixed this instructions... sorry for the confusion!
