### ISSUE TITLE
Analog squelch

### ISSUE THREAD

**Issue by patrickfish** [robotastic/trunk-recorder#6]
Implement RF squelch for analog transmissions.

**Comment by robotastic** [comment]
Do you know much about the GnuRadio Squelch blocks? There are a couple and I am not sure the best to use. In the original SmartNet program, they use Power Squelch, I could try that.

https://github.com/bistromath/gr-smartnet/blob/master/src/python/logging_receiver.py#L41

**Comment by patrickfish** [comment]
I tried (unsuccessfully) to test it on my own branch. I'd be willing to test it if you implemented it.

**Comment by robotastic** [comment]
I just added the code, but it looks like there is an error in Gnuradio where it is not installing a header file correctly. I am going to posted it to the mailing list to get fixed. I will see if I can install the header file locally and make it work.

**Comment by robotastic** [comment]
Closing since there has been no update and the code has been updated to fix a lot of problems.
