### ISSUE TITLE
(error)   stop_recording() - stopping wavfile sink but recorder state is: 1

### ISSUE THREAD

**Issue by no3grover** [robotastic/trunk-recorder#617]
Upgraded from Ubuntu 18.04 to 20.04 and have had a configured SmartNet system for over a year running with no issues, now after upgrade and new compile of latest Trunk-Recorder seeing this error frequently and recorders getting tied up until exhaustion and high CPU.

[2022-01-20 16:50:10.017608] (error)   stop_recording() - stopping wavfile sink but recorder state is: 1

Have tried rebuilding prior version of trunk-recorder and seeing the same behavior so may be related to ubuntu upgrade.  Not sure where to go yet on next step troubleshooting but wanted to open issue to start.

Current config for system and hackrfone

{
    "ver": 2,
    "sources": [{
        "center": 854083750,
        "rate": 16000000,
        "error": 0,
        "ppm": 0,
        "gain": 0,
        "ifGain": 24,
        "bbGain": 22,
        "analogRecorders": 24,
        "driver": "osmosdr",
        "device": "hackrf=26b468dc2e7d848f"
    }],
  "systems": [
    {
      "control_channels": [ 853425000, 853450000, 851812500, 856887500 ],
      "type": "smartnet",
      "bandplan": "800_reband",
      "modulation": "fsk4",
      "squelch": -55,
      "analogLevels": 8,
      "recordUnknown": "true",
      "talkgroupsFile": "tg_604.csv",
      "talkgroupDisplayFormat": "tag_id",
      "shortName": "kcers",
      "minDuration": 0,
	  "broadcastifyApiKey": "yyyyyy",
	  "broadcastifySystemId": "xxx",
	  "hideUnknownTalkgroups": "true",
	  "uploadScript": "encode-local-sys-1.sh"
    }
  ],
  "broadcastifyCallsServer": "https://api.broadcastify.com/call-upload",
  "frequencyFormat": "mhz",
  "callTimeout": 5,
  "defaultMode": "analog",
  "controlWarnRate": 10,
  "logFile": "true",
  "logLevel": "info"
}

**Comment by robotastic** [comment]
Thanks for reporting - It is probably not related to Ubuntu and is more likely due to something I screwed up. 
That error may not actually be a real error. I think with Analog recordings, it might show up every time a recording stops. I have to clean that up.
A couple thoughts:
- it might be worth double checking the squelch value. it is possible it is getting stuck open and keep recording.
- Is the whole system analog?
- Maybe try a short callTimeout

**Comment by jcummingsg2** [comment]
Thanks for the reply, yes I do think its not related to Ubuntu upgrade but rather the version bump on trunk-recorder.  Interestingly, I was seeing this on 4.3.0 but also backed down to prior running code 4.2.0 and still seeing the error in the logs but it  does not seem to be tying up all the analog recorders anymore and its been running for about an hour an a half now and looking better.  I did not check squelch, that's a good thought and had not looked into that yet, will do this evening.

**Comment by ZL1LAC** [comment]
Can confirm I'm also getting the same issue with the stopping wavfile sink but recorder state.

I'm running this in Docker using a Pi3B+.

Here is my config file.
```
{
	"ver": 2,
"sources": [{
	"center": 141400000,
	"rate": 2048000,
	"gain": 16.6,
	"analogRecorders": 1,
	"driver": "osmosdr",
	"device": "rtl=0"
}],
"systems": [
{
	"type": "conventional",
	"defaultMode": "analog",
	"channels": [141400000],
	"shortName": "EAS",
	"minDuration": 3,
	"callLog": false,
	"audioArchive": true,
	"squelch": -50
	}],
	"captureDir": "/home/pi/recorder/radio/"
}
```

**Comment by robotastic** [comment]
This is probably resolved in current versions, but please reopen if it is not
