### ISSUE TITLE
Correct package name

### ISSUE THREAD

**Issue by tdduarte** [robotastic/trunk-recorder#619]
Instructions on installing on raspberry pi has the following:  
sudo apt -y install libssl-dev openssl curl git fdkaac sox libcurl3-gnutls libcurl4 libcurl4-openssl-dev gnuradio gnuradio-dev gr-osmosdr libhackrf-dev libuhd-dev cmake make build-essential libboost-all-dev libusb-1.0-0.dev 

Looks like libusb-1.0-0.dev  should be libusb-1.0-0-dev

**Comment by Dewey3** [comment]
Correct... reported here:  https://github.com/robotastic/trunk-recorder/issues/599

**Comment by robotastic** [comment]
Thanks @Dewey3 @tdduarte  and sorry for not fixing this sooner. Just patched it.
