### ISSUE TITLE
docker start "Creating network "liquidsoap_default" with the default driver"

### ISSUE THREAD

**Issue by hayden-t** [robotastic/trunk-recorder#639]
so i use docker-compose up
and it says at start the title of the issue

where does this come from ? i dont have liquid soap installed yet or any reference to it,

**Comment by jodfie** [comment]
It’s the name of the directory that you have the Docker-compose file in.

**Comment by hayden-t** [comment]
Ah thanks ! I figured it must have been me, just its in a folder called liquidsoap! :)
