### ISSUE TITLE
silenceFrames got switched back to idleSilence at main.cc#465

### ISSUE THREAD

**Issue by rosecitytransit** [robotastic/trunk-recorder#647]
https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/main.cc#L465

happened in https://github.com/robotastic/trunk-recorder/commit/70698818065b24a494fc5488c82445609eab9ebc

`idleSilence` doesn't appear anywhere else in the code

(this is a fix I originally committed with #456 / #470 )

**Comment by robotastic** [comment]
Weird! I don't know why that snuck in there... thanks for catching it!

**Comment by rosecitytransit** [comment]
You're welcome. Also, I'm not sure it's listed in the configuration docs, though I don't know this option is really useful anyways
