### ISSUE TITLE
(error)   Failed to convert call recording, see above error. Make sure you have sox and fdkaac installed.

### ISSUE THREAD

**Issue by b1tninja** [robotastic/trunk-recorder#656]
https://github.com/robotastic/trunk-recorder/blob/36aae6b5d16e8f11e4a6944f29936fa0d9d55046/trunk-recorder/call_concluder/call_concluder.cc#L35

Turns our, when convert_media was being called, the build of sox 14.4.2 I have was segfaulting parsing the options, 
```
  int nchars = snprintf(shell_command, 400, "sox %s --norm -t wav - | fdkaac --silent  -p 2 --ignorelength -b 8000 -o %s -", filename, converted);
```

Sox Backtrace
```
#0  0x00007f9fc4ff54bd in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007f9fc4f120c3 in strdup () from /usr/lib/libc.so.6
#2  0x00007f9fc517b9ee in lsx_strdup (s=<optimized out>) at xmalloc.c:72
#3  0x000055c27a551aab in parse_gopts_and_fopts (f=f@entry=0x7ffe3d393740) at sox.c:2370
#4  0x000055c27a553c3b in parse_options_and_filenames (argc=argc@entry=5, argv=argv@entry=0x7ffe3d393d18) at sox.c:2654
#5  0x000055c27a54c123 in main (argc=5, argv=0x7ffe3d393d18) at sox.c:2885
```

https://github.com/mansr/sox/blob/sox-14.4.2/src/sox.c#L2370
```
        norm_level = lsx_strdup(optstate.arg);
```

The issue seems to be in the parsing of the `--norm` option, I will try to come up with a PR, `--norm=-nh -G` seems like it might work

**Comment by robotastic** [comment]
Thanks! This should be fixed now. I set the normalization value back to what it was originally.... -0.01
