### ISSUE TITLE
Talkgroups File Loaded Repeatedly

### ISSUE THREAD

**Issue by tadscottsmith** [robotastic/trunk-recorder#658]
It looks like the loading of the talkgroups was mistakenly moved inside the control channel loop. I'm assuming this was an accident? It's currently being read in once for every control channel rather than once per system.

https://github.com/robotastic/trunk-recorder/blob/d616a861894c3f3e81cd2ad3fd6b9bcb652a239e/trunk-recorder/main.cc#L267

**Comment by rosecitytransit** [comment]
I've noticed that (in the output logs) too

**Comment by tadscottsmith** [comment]
Thank you!!

**Comment by rosecitytransit** [comment]
FWIW, it looks like it had been changed with https://github.com/robotastic/trunk-recorder/commit/131671308f8dcc96ed0d7767367e621b661e28eb
