### ISSUE TITLE
Could NOT find MPIR - Could NOT find GnuradioOsmosdr

### ISSUE THREAD

**Issue by Dewey3** [robotastic/trunk-recorder#672]
Doing a fresh build of the latest release and came across these two errors (maybe they're on my end, but I just don't know):

![CouldNotFindMPIR](https://user-images.githubusercontent.com/36827358/164259411-4809b1be-573e-4200-9643-47127715b9b3.jpg)

**Comment by dmonies327** [comment]
Same problem on a fresh install of Lubuntu, did you get this resolved?

**Comment by e850205** [comment]
Same problem when trying to install v5

**Comment by ZeroChaos-** [comment]
The original post has no error, just a warning that optional things are not found.  Mpir isn't needed (gmp is used first anyway) and depending on your hardware gr-osmosdr is not needed.  That said, for most folks it is, so maybe install it (and the development packages for your distro)
