### ISSUE TITLE
Should Raspberry Pi Users Change the Buster Name to Bullseye?

### ISSUE THREAD

**Issue by Dewey3** [robotastic/trunk-recorder#683]
I was just pursuing over the Raspberry Pi setup instructions when I realized that a part of the setup reads to add  `deb http://www.deb-multimedia.org/ buster main non-free`  to /etc/apt/sources.list.  Since the Raspberry Pi has been using Bullseye for a while now, that made me wonder if I should change `buster` to `bullseye`, so I visited the http://www.deb-multimedia.org/ webpage.  According to the webpage, screenshot attached, we should now be using `bullseye` instead of `buster`.  Should we now be using `bullseye` instead of `buster` on the line that we add to /etc/apt/sources.list?

![20220512-161730_Image](https://user-images.githubusercontent.com/36827358/168162076-b9e4e30b-494f-4676-b3da-770066c57b9b.jpg)

**Comment by Dygear** [comment]
Ha! I'm actually making a PR for that right now. Along with general house keeping stuff for the Buster -> Bullseye transition and the newer software stack (including using 64bit by default).
