### ISSUE TITLE
build failure - spurious character got committed in trunk-recorder/trunk-recorder/trunk-recorder/systems/system.h line 40

### ISSUE THREAD

**Issue by rabarar** [robotastic/trunk-recorder#686]
looks like a 'ß' was added to the end of line 40 of `system.h` making the compile barf...

**Comment by Dewey3** [comment]
Yea, that got reported and included another file a little earlier here:  [https://github.com/robotastic/trunk-recorder/pull/684](url).

**Comment by robotastic** [comment]
Closing this out be because I think it was fixed.
