### ISSUE TITLE
Build fails with gnuradio 3.10+ due to removal of deprecated udp_sink block

### ISSUE THREAD

**Issue by mldulaney** [robotastic/trunk-recorder#694]
gnuradio commit 50c48b3321d59ff6fa296d672a723787f32e5345
https://github.com/gnuradio/gnuradio/commit/50c48b3321d59ff6fa296d672a723787f32e5345

Gnuradio removed the udp_sink blocks in favor of network/udp_sink.

**Comment by robotastic** [comment]
This pull request should fix this. Can you give it a try and report back?

**Comment by mldulaney** [comment]
Which pull request?

**Comment by mldulaney** [comment]
I got it to build with some effort.  Guess I'll need to open a pull request against the pull request.

**Comment by Dygear** [comment]
https://github.com/robotastic/trunk-recorder/pull/682

Just confirmed that this PR fixes this on Ubuntu 22.04 LTS arm64 (Raspberry Pi)

**Comment by robotastic** [comment]
Cool! happy to hear it is building
