### ISSUE TITLE
Build fails trunk-recorder/gr_blocks/transmission_sink.cc:87:10: error: 'boost::filesystem' has not been declared

### ISSUE THREAD

**Issue by mldulaney** [robotastic/trunk-recorder#699]
Seems like this is part of the boost removal project; putting the import back into the header file resolves the build issue.

**Comment by photounit** [comment]
Right now NONE of the Ubuntu builds work....   Can you tell me how exactly you resolved this as it doesn't seem like their is any interest in getting the builds fixed... Thanks!

**Comment by robotastic** [comment]
I just rolled in a PR which may fix this... If it doesn't, can you post a copy of the build error and which version of Ubuntu you are having trouble with?
