### ISSUE TITLE
Missing log messages about missed recording due to not covering the frequency

### ISSUE THREAD

**Issue by kb2ear** [robotastic/trunk-recorder#705]
There used to be messages that were printed in the logs:
```
 Freq:   0.000000 MHz    Not Recording: no source covering Freq
```
This was quite useful in figuring out if the sources need adjustment or if the system added channels and I need more sources. The don't appear to be printed anymore. Can we get them back?

**Comment by theficus** [comment]
Was there a reason this was removed? This log entry seems extremely useful.

**Comment by robotastic** [comment]
Should be fixed now.
