### ISSUE TITLE
Need for tips how to find best gain settings?

### ISSUE THREAD

**Issue by LoveScanner** [robotastic/trunk-recorder#710]
I usually use Sdrtrunk (Airspy mini dongle),
with gain
mode settings: lienarity
master: 13

Now when I try to use Trunk-recorder I have a lot of settings
ifGain / mixGain / lnaGain / tiaGain / pgaGain / gain
I could not understand how I discover the most recommended situation there are suggestions?

**Comment by robotastic** [comment]
closing for now because I am not sure of what is best for airspy - feel free to reopen if someone has the answer
