### ISSUE TITLE
Passing Arguments to UHD Appears To Be Either Unsupported or Undocumented

### ISSUE THREAD

**Issue by faultywarrior** [robotastic/trunk-recorder#718]
There does not appear to be a way to pass arguments to the UHD driver that is documented.  It's not clear if Trunk Recorder does not support doing this at all; or if the docs just need to be updated to reflect how to use the "device" field in the config file to pass arguments to UHD like it can be for osmosdr.

This would be of great help to those of us with USRP B210s (or really any of the dual frontend USRPs) so that we could set each frontend as a source and use them in separate bands.

**Comment by robotastic** [comment]
This isn't supported - if this is still an issue, please reopen and provide an example. It may need to be set using a function call vs being an argument passed to the driver.
