### ISSUE TITLE
-DBUILD_SHARED_LIBS=ON slightly broken on make install

### ISSUE THREAD

**Issue by ZeroChaos-** [robotastic/trunk-recorder#722]
When I install, I get a warning from the package manager.
```
 * QA Notice: Unresolved soname dependencies:
 * 
 * 	/usr/bin/trunk-recorder: libgit.so
 * 
 * QA Notice: Symbolic link /usr/include/trunk-recorder/git.h points to /usr/include/git.h which does not exist.
```
Now, there are two problems here.
1.) libgit.so should be installed when building shared
2.) A dangling symlink is installed instead of the actual git.h file.

For number 2, to be honest, I'm not even sure why the includes are shipped at all?  Is this for external plugins maybe?  Either way, I'm not sure why the git.h file is a symlink in the first place, maybe just move everything into trunk-recorder together? 

As for number 1, I don't have an obvious fix.  I'm assuming cmake has an option to install solibs when built shared, but I'm not sure what it is off hand.

**Comment by robotastic** [comment]
I think the git approach has been changed... happy to dig in for a fix if not
