### ISSUE TITLE
Air spy R2 will not work with second SDR

### ISSUE THREAD

**Issue by nycode802** [robotastic/trunk-recorder#742]
It appears that the air spy R2 will not work with any other sdrs plugged in, my system works fine until I plug in my second air spy or rtl it throws all kind of errors

**Comment by nycode802** [comment]
It’s throws P25 Parse errors just by having it plugged in and not even assigned in the config

**Comment by johnrockie** [comment]
What is your config? I believe the latest update makes it so that you have to point the Airspy in the config and can no longer use
`"device": "airspy",`
Check out #737 and maybe that fixes it for you also

**Comment by nycode802** [comment]
{
    "ver": 2,
    "sources": [


{
        "center": 852303125.0,
        "rate": "10000000.0",
        "error": 0,
        "gain":20,
        "antenna": "RX",
        "digitalRecorders": 15,
        "driver": "osmosdr",
        "device": "airspy=0xB58069DC39614B13"
   },{
       "center": 772228125.0,
       "rate": "10000000.0",
       "error": 0,
       "gain":20,
       "antenna": "RX",
       "digitalRecorders": 15,
       "driver": "osmosdr",
       "device": "airspy=0x744C60C82162104F"
  }


],
    "systems": [


        {
        "control_channels": [851162500.0,852425000.0,852675000.0,852737500.0],
        "type": "p25",
        "talkgroupsFile": "suffolk.csv",
        "shortName": "Suffolk_County_Project_800",
        "modulation": "qpsk",
        "audioArchive":false,
        "transmissionArchive":false,
        "callLog":false,
        "digitalLevels":1,
        "talkgroupDisplayFormat":"tag_id",
        "compressWav":true

    }, {
        "control_channels": [772281250.0,772918750.0,773656250.0,774156250.0],
        "type": "p25",
        "talkgroupsFile": "suffolk.csv",
        "shortName": "Suffolk_County_Project_25",
        "modulation": "qpsk",
        "audioArchive":false,
        "transmissionArchive":false,
        "callLog":false,
        "digitalLevels":1,
        "talkgroupDisplayFormat":"tag_id",
        "compressWav":true

    }


    ],"plugins": [{
        "name": "rdioscanner_uploader",
        "library": "librdioscanner_uploader.so",
        "server": "http://suffolkscanner.com:3000",
        "systems": [{
            "shortName": "Suffolk_County_Project_25",
            "apiKey": "",
            "systemId": 1 
        }]
    }]

}

**Comment by nycode802** [comment]
> What is your config? I believe the latest update makes it so that you have to point the Airspy in the config and can no longer use
> `"device": "airspy",`
> Check out #737 and maybe that fixes it for you also

{
    "ver": 2,
    "sources": [


{
        "center": 852303125.0,
        "rate": "10000000.0",
        "error": 0,
        "gain":0,
        "antenna": "RX",
        "digitalRecorders": 15,
        "driver": "osmosdr",
        "device": "airspy=0xB58069DC39614B13"
   },{
       "center": 772228125.0,
       "rate": "10000000.0",
       "error": 0,
       "gain":0,
       "antenna": "RX",
       "digitalRecorders": 15,
       "driver": "osmosdr",
       "device": "airspy=0x744C60C82162104F"
  }


],
    "systems": [


        {
        "control_channels": [851162500.0,852425000.0,852675000.0,852737500.0],
        "type": "p25",
        "talkgroupsFile": "suffolk.csv",
        "shortName": "Suffolk_County_Project_800",
        "modulation": "qpsk",
        "audioArchive":false,
        "transmissionArchive":false,
        "callLog":false,
        "digitalLevels":1,
        "talkgroupDisplayFormat":"tag_id",
        "compressWav":true

    }, {
        "control_channels": [772281250.0,772918750.0,773656250.0,774156250.0],
        "type": "p25",
        "talkgroupsFile": "suffolk.csv",
        "shortName": "Suffolk_County_Project_25",
        "modulation": "qpsk",
        "audioArchive":false,
        "transmissionArchive":false,
        "callLog":false,
        "digitalLevels":1,
        "talkgroupDisplayFormat":"tag_id",
        "compressWav":true

    }


    ],"plugins": [{
        "name": "rdioscanner_uploader",
        "library": "librdioscanner_uploader.so",
        "server": "http://suffolkscanner.com:3000",
        "systems": [{
            "shortName": "Suffolk_County_Project_25",
            "apiKey": "",
            "systemId": 1 
        }]
    }]

}

**Comment by robotastic** [comment]
I think multiple airpsy issue got addressed - please reopen if it didn't
