### ISSUE TITLE
High Error Values With A HackRF Causes Control Channel Search To Hang

### ISSUE THREAD

**Issue by faultywarrior** [robotastic/trunk-recorder#746]
As discussed in Discord, if you set the error to a very high value (17600 in my case); TR hangs when attempting to try the first control channel.  It just sits and does nothing, with the last line of output: "[2022-12-16 21:17:35.138714] (info)      P25 Trunking ARB - Initial Rate: 10000000 Resampled Rate: 25000 Initial Decimation: 100 System Rate: 24000 ARB Rate: 0.96".  Eventually, it will output the recorder status, with all said to be available; however TR never attempts to even cycle through control channels nor decode them.

If you set the value to something much smaller - say under 10000 - it works fine.  In my case, setting the value to 0 allowed TR to lock onto the control channel and decode calls perfectly.  Only tested in QPSK mode.

**Comment by robotastic** [comment]
closing - please reopen if this is still an issue with the current version
