### ISSUE TITLE
AirSpy will not work without serial number specified.

### ISSUE THREAD

**Issue by lf73** [robotastic/trunk-recorder#761]
Using version 4.03 docker image

As per Wiki, should be able to specify "airspy" for device and it will open the first connected Airspy device. However, it appears to be trying to open another Serial Number by default, than my own.

Attempting to open airspy by s/n= 0x0000152309C032A4
[2023-01-05 20:01:28.101229] (error)   Failed parsing Config: Failed to open AirSpy device (-5) AIRSPY_ERROR_NOT_FOUND

This is not my serial number. And, again, only, specified "device": "airspy"

I found a workaround by calling Airspy Info to get my serial number and then specifying that number as "airspy=0x1234567...."

No idea of where 0x0000152309C032A4 came from... Perhaps hardcoded somewhere in source.. Or some kind of bad lookup when initializing osmosdr driver?

**Comment by robotastic** [comment]
Closing this out - please reopen if there is more info
