### ISSUE TITLE
Message from Docker 'device veth entered promiscuous mode'

### ISSUE THREAD

**Issue by smokedsalmonbagel** [robotastic/trunk-recorder#765]
Not sure if this is a Docker issue or an issue with trunk-recorder but I am seeing many messages repeating like this when I run `sudo dmesg`
```
[ 3327.059193] device veth38cc426 left promiscuous mode
[ 3327.059207] br-b6f800f969ee: port 1(veth38cc426) entered disabled state
[ 3387.000912] br-b6f800f969ee: port 1(vethb1dd84e) entered blocking state
[ 3387.000924] br-b6f800f969ee: port 1(vethb1dd84e) entered disabled state
[ 3387.001631] device vethb1dd84e entered promiscuous mode
[ 3387.936493] eth0: renamed from vethe172cbc
```
This was on two different machines - Both Ubuntu 22.04.
When I stopped the docker daemon the messages stopped.  Is anyone else seeing these messages?

**Comment by robotastic** [comment]
Closing this out - please reopen if it is still an issue
