### ISSUE TITLE
Build Failure on OSX (Monterey/Ventura) on current codebase

### ISSUE THREAD

**Issue by rabarar** [robotastic/trunk-recorder#766]
Under OSX, build fails to compile. Environment includes:

Xcode 14 lastest release
gnuadio 3.10.5.0

**Comment by rabarar** [comment]
the compilation that fails:

```
In file included from /Users/robert/src/sdr/trunk-recorder/lib/op25_repeater/lib/frame_assembler_impl.cc:26:
/Users/robert/src/sdr/trunk-recorder/lib/op25_repeater/lib/frame_assembler_impl.h:47:52: error: implicit instantiation of undefined template 'std::array<std::deque<short>, 2>'
                std::array<std::deque<int16_t>, 2> output_queue;
                                                   ^
```

**Comment by rabarar** [comment]
SOLUTION: adding `<array>` to `trunk-recorder/lib/op25_repeater/lib/frame_assembler_impl.h` fixes the compilation and results in a successful build

**Comment by robotastic** [comment]
Thanks for the fix! just made it

**Comment by rabarar** [comment]
Anytime!On Feb 6, 2023, at 9:02 PM, Luke Berndt ***@***.***> wrote:﻿
Thanks for the fix! just made it
