### ISSUE TITLE
Discord Server Link Invalid

### ISSUE THREAD

**Issue by Gibby** [robotastic/trunk-recorder#769]
Trying to join the Discord server, however, clicking the link says the invite is invalid or expired.

![image](https://user-images.githubusercontent.com/503761/217324032-8cbc4437-c0e6-47d5-8cc3-eb310a5c7c64.png)

**Comment by taclane** [comment]
Here's a non-expiring invite for anyone who is looking for it until the previous link gets fixed.

https://discord.gg/rcynHG2AvR

**Comment by taclane** [comment]
The vanity URL should now be working again if you want to close this out.

https://discord.gg/trunk-recorder
