### ISSUE TITLE
config.json wiki documentation link

### ISSUE THREAD

**Issue by smokedsalmonbagel** [robotastic/trunk-recorder#786]
I think the link for the wiki page with the config parameters: 
https://github.com/robotastic/trunk-recorder/wiki/Configuring-a-System
Should point here:
https://github.com/robotastic/trunk-recorder/blob/master/docs/CONFIGURE.md
or at least be updated.  I guess I can make the edit but not sure what the best way to do this is or if it is intentionally a different page.

**Comment by robotastic** [comment]
yea... the wiki is sort of a hot mess. I should prob just close it down and have people update that docs instead.
