### ISSUE TITLE
Aviation band / AM receiver(s)

### ISSUE THREAD

**Issue by dthomson134** [robotastic/trunk-recorder#825]
I use Trunk-Recorder for P25 systems.  It flawlessly records three medium sized simulcast systems.
I would like to also record aviation band (118-137 MHz) AM signals.
Is that possible?

Thanks,
Dave

**Comment by robotastic** [comment]
AM recording is not on the roadmap right now... there are a bunch of good tools for handling this.... atleast that is my impression. Happy to reconsider if there is something unique that trunk recorder would add
