### ISSUE TITLE
Cannot open udp-debug.grc in gnuradio-companion because of missing block

### ISSUE THREAD

**Issue by theficus** [robotastic/trunk-recorder#841]
I'm trying to load udp-debug.grc in gnuradio-companion 3.10.7.0 on MacOS. It is unable to find blocks_udp_source.

<img width="725" alt="image" src="https://github.com/robotastic/trunk-recorder/assets/11638244/dc4608ba-2176-44cb-b884-6f0dbf925995">

**Comment by taclane** [comment]
Somewhere along the way, the UDP block got renamed in gnuradio.  

If you open up the .grc file in a text editor and change all instances of `blocks_udp_source` to `network_udp_source`, it should be all that is needed.

**Comment by robotastic** [comment]
Updated the blocks - thanks @taclane  - no idea if UDP debugging still works though
