### ISSUE TITLE
Curl missing from docker image

### ISSUE THREAD

**Issue by arcreigh** [robotastic/trunk-recorder#850]
Looks like curl is missing from the latest image, I use it for rdio-scanner uploads can we get this re-implemented?

**Comment by Dewey3** [comment]
I don't know if it's related, but if it helps whoever ultimately looks at this, I got ton of curl warning when doing a non-Docker build today.  The `make` file log is attached and the curl warnings start at 91%.

[TrunkRecorderInstallationWarnings.txt](https://github.com/robotastic/trunk-recorder/files/13257631/TrunkRecorderInstallationWarnings.txt)

**Comment by taclane** [comment]
> I don't know if it's related, but if it helps whoever ultimately looks at this, I got a ton of curl depreciated warnings when doing a non-Docker build today. The `make` file log is attached and the curl warnings start at 91%.
> 
> [TrunkRecorderInstallationWarnings.txt](https://github.com/robotastic/trunk-recorder/files/13257631/TrunkRecorderInstallationWarnings.txt)

That's unrelated to the docker issue.  The curl libraries got an update a little while back, and is recommending that the plugins switch over to some new functions because the methods currently used will stop working someday.  It'll get fixed eventually, but the huge wall of compile warnings can be ignored for now.

> Looks like curl is missing from the latest image, I use it for rdio-scanner uploads can we get this re-implemented?

I can't speak for what's up with curl, but is using the rdio-scanner plugin an option?  As long as you don't have any sort of complicated upload logic, and are using rdio-scanner 6.0 or greater, it seems to be the preferred method over upload scripts.

**Comment by 0lav** [comment]
> > I don't know if it's related, but if it helps whoever ultimately looks at this, I got a ton of curl depreciated warnings when doing a non-Docker build today. The `make` file log is attached and the curl warnings start at 91%.
> > [TrunkRecorderInstallationWarnings.txt](https://github.com/robotastic/trunk-recorder/files/13257631/TrunkRecorderInstallationWarnings.txt)
> 
> That's unrelated to the docker issue. The curl libraries got an update a little while back, and is recommending that the plugins switch over to some new functions because the methods currently used will stop working someday. It'll get fixed eventually, but the huge wall of compile warnings can be ignored for now.
> 
> > Looks like curl is missing from the latest image, I use it for rdio-scanner uploads can we get this re-implemented?
> 
> I can't speak for what's up with curl, but is using the rdio-scanner plugin an option? As long as you don't have any sort of complicated upload logic, and are using rdio-scanner 6.0 or greater, it seems to be the preferred method over upload scripts.

I just open the docker console and do apt-get update then apt-get install curl to fix.

**Comment by robotastic** [comment]
Closing - looks like Curl is back in the image
