### ISSUE TITLE
Airspy install libraries on Raspberry pi install

### ISSUE THREAD

**Issue by jeffbarclay** [robotastic/trunk-recorder#879]
Creating new sets on the RPI with the Airspy SDR - running into same problem as the initial Mac install, don't know how to update/add the libraries via the Pi since Im not using homebrew???

this was the initial install line:
`sudo apt -y install libssl-dev openssl curl git fdkaac sox libcurl3-gnutls libcurl4 libcurl4-openssl-dev gnuradio gnuradio-dev gr-osmosdr libhackrf-dev libuhd-dev cmake make build-essential libboost-all-dev libusb-1.0-0-dev libsndfile1-dev`

Previous solution:

              You're fine.  All you're essentially going to do is rebuild gr-osmosdr (with airspy drivers), install it on top of whatever you did previously, then do the same with trunk-recorder.

If you're following along the trunk-recorder mac homebrew directions, all you should really need to do is restart from the middle of the "Install the OsmoSDR Package for GNURadio" step.  `cd` into the `build` directory, do a `make clean` and the continue on from the `cmake ..` step. After the cmake, you should see the airspy drivers in the "Gnuradio enabled components" printout.

Afterwards, do the same general thing with trunk-recorder.  Clean out the build directory, then resume from the cmake step.

_Originally posted by @taclane in https://github.com/robotastic/trunk-recorder/issues/849#issuecomment-1783152288_

**Comment by robotastic** [comment]
Closing - please reopen if it is still an issue
