### ISSUE TITLE
thread_body_wrapper "Buffer too small for min_noutput_items" errors in 4.7

### ISSUE THREAD

**Issue by bnazari** [robotastic/trunk-recorder#884]
First of all, this project is absolutely incredible. Dove into a few weeks ago and now I have a system with 8 RTL-SDRs on it, recording about 40k calls/day. Everything has been working like a charm after I got it dialed in. 

So today, I decided to bump it to the 4.7 release and noticed a bunch of overrun issues and this error repeated continually:
"thread_body_wrapper :error: ERROR thread[thread-per-block[27]: <block fft_filter_ccf(2027)>]: Buffer too small for min_noutput_items"

I suspect it has to do with the new OP25 integration, as pulling the commit from Nov. 28 runs just fine.  Running Ubuntu 23.10 and the package install of GR is 3.10.7.0, if that provides any insight.  System is recording 4 trunked P25 systems and a few conventional analog ones. 

Please let me know if I can contribute in any way. I didn't want to flood the post with massive log and config dumps.

**Comment by taclane** [comment]
I just noticed the same thing.  Seems like it's specifically with conventional analog.  

Either disabling those systems, or rolling back to the 23e3d9f commit or earlier seems to get things back on track.
