### ISSUE TITLE
Understanding smartnet CMDs

### ISSUE THREAD

**Issue by jonathanendersby** [robotastic/trunk-recorder#91]
Hi, firstly let me just say that this is a great community and thank you to everyone who has helped me so far. (I realise I'm misusing the issues tracker, but this seem where most of the momentum is... please shout at me if I should use the Google group instead?)

I'm hoping someone can shed some light on the following.

I have a trunk that I am monitoring and am trying to reconcile how its CMD values (eg. the variable passed to getfreq()) is mapped to the LCN value that unitrunker is reporting on the same trunk. At first glance they appear to be off by a 2 (ie Unitrunker reports 431, but the closest cmd I see is 433)... and then sometimes I stop receiving 433 entirely and for hours I'll receive 434  (and no 433 or 431, even though unitrunker is happily using/reporting 431 the whole time). Do I sound confused? 

Could this be an issue with how the int value of cmd is determined from whatever modulation the trunk is using?  

I'm going to leave this logging throughout the day to get a better idea of which cmds I'm getting and if they are indeed changing.

**Comment by robotastic** [comment]
The latest version that is in develop has better support for the SmartNet bandplans. I think it might be solved there.
