### ISSUE TITLE
5.0 RC - Cannot tune to channel anymore

### ISSUE THREAD

**Issue by theficus** [robotastic/trunk-recorder#913]
Using identical configs from the latest master branch, I'm unable to lock onto any control channel. I've attached my log file for reference.

[01-25-2024_1934_00.log](https://github.com/robotastic/trunk-recorder/files/14060035/01-25-2024_1934_00.log)

Previously discussed here: https://github.com/robotastic/trunk-recorder/issues/836#issuecomment-1882370439 but I gave it another attempt with the latest RC branch since the test branch I had been using seems to be gone now.

**Comment by robotastic** [comment]
Can you include a copy of your config file? I will give a try running it with a local system and see what happens.

**Comment by robotastic** [comment]
Just patched up a bug that might have been causing this. Can you try pulling the latest in this branch and giving it a try?

**Comment by theficus** [comment]
I'll give it a try and report back. Thanks!

**Comment by theficus** [comment]
@robotastic works perfectly after your latest commits. Thanks!
