### ISSUE TITLE
add signal (and noise?) into json

### ISSUE THREAD

**Issue by ZeroChaos-** [robotastic/trunk-recorder#923]
TR now outputs signal level every three minutes in a big status report.  It would be great to add that signal information (and noise if available) into the json.  This would allow a much faster tuning as well as the ability to take a longer average across each system.

**Comment by bburkett52** [comment]
I guess I am really overlooking something so where and how can I see this
signal info? Is it setup in the config.json file? Where does it show up?

Thanks for all the work on this program! I've been running the rc5 version
and updating as work progresses. I'm only monitoring 1 P25P2 system and all
is good!

Regards,
~Bob

**Comment by ZeroChaos-** [comment]
complete, in 5.0 release
