### ISSUE TITLE
Newly Released 7/24 v5.0.0

### ISSUE THREAD

**Issue by Dewey3** [robotastic/trunk-recorder#964]
Greetings all.  I just installed the newly released 7/24/2024, v5.0.0.  **First, thank you**, I appreciate all of the brilliant minds that go into making TrunkRecorder betterer and betterer.  FYI only, I am still seeing the two issues I observed in the previous, but later v4 updates and v5 release candidates.

The first is the installation error when installing to Raspberry Pi OS 64 Lite (bookworm):  https://github.com/robotastic/trunk-recorder/issues/938

The second is that it still cannot keep up with updating the UIDs on the busy Prince George's County, Maryland system (https://www.radioreference.com/db/sid/6341) when transmissions are rapid fire back-to-back:  https://github.com/robotastic/trunk-recorder/issues/836

Again, I appreciate all of the contributing brilliant minds, this not a complaint, but a FYI.

**Comment by robotastic** [comment]
Closing this - tracking through #836
